import { readFileSync, writeFileSync } from 'node:fs'
import { PERMISSION_CATALOGUE, PermissionKey } from '../src/permissions.ts'
import { ROLE_TEMPLATES, RoleKey } from '../src/role-templates.ts'

export const outputPath = new URL('../../../docs/auth/PERMISSION_MATRIX.generated.md', import.meta.url)
export function renderMatrix() {
  const lines = [
    '# Exact permission matrix', '',
    'Generated by `pnpm --filter @erp/contracts docs:generate`. Edit the source catalogue and role templates, then regenerate.', '',
    'Each cell lists independent allowed scopes. `—` means no grant. Reserved actions cannot be granted. MFA depends on the role and the privileged scopes shown below; this table is not a policy evaluator.', '',
    `| Permission | Availability | Privileged scopes | ${RoleKey.options.join(' | ')} |`,
    `|---|---|---|${RoleKey.options.map(() => '---').join('|')}|`,
  ]
  for (const permission of PermissionKey.options) {
    const metadata = PERMISSION_CATALOGUE[permission]
    const cells = RoleKey.options.map((role) => ROLE_TEMPLATES[role].grants
      .filter((grant) => grant.permission === permission).map((grant) => grant.scope).join(', ') || '—')
    lines.push(`| \`${permission}\` | ${metadata.availability} | ${metadata.privilegedScopes.join(', ') || '—'} | ${cells.join(' | ')} |`)
  }
  return lines.join('\n') + '\n'
}
if (process.argv.includes('--write')) writeFileSync(outputPath, renderMatrix())
if (process.argv.includes('--check') && readFileSync(outputPath, 'utf8') !== renderMatrix()) {
  throw new Error('Permission matrix is stale. Run docs:generate.')
}
