import { sql } from 'drizzle-orm'
import {
  bigint,
  boolean,
  date,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  primaryKey,
  smallint,
  text,
  timestamp,
  unique,
  uuid,
} from 'drizzle-orm/pg-core'

/**
 * Drizzle's typed view of the tenant tables. The migration is authoritative for
 * RLS, triggers and cross-table constraints that cannot be represented safely
 * in an ORM declaration.
 */
const id = () => uuid('id').defaultRandom().primaryKey()
const tenant = () => uuid('school_id').notNull()
const timestamps = () => ({
  createdAt: timestamp('created_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
})

export const membershipStatus = pgEnum('membership_status', [
  'active',
  'suspended',
  'removed',
])
export const membershipKind = pgEnum('membership_kind', ['adult', 'student'])
export const invitationStatus = pgEnum('invitation_status', [
  'pending',
  'accepted',
  'revoked',
  'expired',
])
export const accessEffect = pgEnum('access_effect', ['allow', 'deny'])
export const deliveryStatus = pgEnum('delivery_status', [
  'queued',
  'processing',
  'sent',
  'failed',
  'dead_letter',
])

// Better Auth core + phone + two-factor plugin tables. They deliberately have
// no school_id: identity is global and is never selected through tenant RLS.
export const authUsers = pgTable('auth_user', {
  id: id(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('email_verified').notNull().default(false),
  image: text('image'),
  phoneNumber: text('phone_number').unique(),
  phoneNumberVerified: boolean('phone_number_verified')
    .notNull()
    .default(false),
  twoFactorEnabled: boolean('two_factor_enabled').notNull().default(false),
  // Lockout and disable live on the identity, because no school owns it. See
  // migration 0010.
  disabledAt: timestamp('disabled_at', { withTimezone: true }),
  lockedUntil: timestamp('locked_until', { withTimezone: true }),
  failedSignIns: integer('failed_sign_ins').notNull().default(0),
  // Set when the password was generated by the school and sent by text
  // message; cleared when the person chooses their own. See migration 0019.
  mustChangePassword: boolean('must_change_password').notNull().default(false),
  ...timestamps(),
})
export const authSessions = pgTable(
  'auth_session',
  {
    id: id(),
    token: text('token').notNull().unique(),
    userId: uuid('user_id')
      .notNull()
      .references(() => authUsers.id, { onDelete: 'cascade' }),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    mfaVerifiedAt: timestamp('mfa_verified_at', { withTimezone: true }),
    sharedDevice: boolean('shared_device').notNull().default(false),
    ...timestamps(),
  },
  (t) => [index('auth_session_user_idx').on(t.userId)],
)
// Better Auth rateLimit model with storage "database". Global auth table.
export const authRateLimit = pgTable('auth_rate_limit', {
  id: id(),
  key: text('key').notNull().unique(),
  count: integer('count').notNull().default(0),
  lastRequest: bigint('last_request', { mode: 'number' }).notNull().default(0),
})
// Our own throttling store: budgets Better Auth must not prune.
export const authThrottle = pgTable('auth_throttle', {
  id: id(),
  key: text('key').notNull().unique(),
  count: integer('count').notNull().default(0),
  lastRequest: bigint('last_request', { mode: 'number' }).notNull().default(0),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
})
/** Text messages a test build holds instead of sending. See migration 0008. */
export const heldSms = pgTable('held_sms', {
  id: id(),
  recipient: text('recipient').notNull(),
  purpose: text('purpose').notNull(),
  secret: text('secret').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
})
/**
 * One row per /api request: the route pattern only, never the URL, query
 * string, body or user agent. Global infrastructure table, no tenant policy and
 * no foreign keys, so a row survives what it names. See migration 0010.
 */
export const accessLog = pgTable(
  'access_log',
  {
    id: id(),
    at: timestamp('at', { withTimezone: true }).notNull().defaultNow(),
    method: text('method').notNull(),
    route: text('route').notNull(),
    status: integer('status').notNull(),
    code: text('code'),
    userId: uuid('user_id'),
    membershipId: uuid('membership_id'),
    schoolId: uuid('school_id'),
    ipHash: text('ip_hash'),
    durationMs: integer('duration_ms').notNull(),
    requestId: text('request_id').notNull(),
  },
  (t) => [
    index('access_log_at_idx').on(t.at),
    index('access_log_membership_idx').on(t.membershipId, t.at),
  ],
)
export const authAccounts = pgTable(
  'auth_account',
  {
    id: id(),
    accountId: text('account_id').notNull(),
    providerId: text('provider_id').notNull(),
    userId: uuid('user_id')
      .notNull()
      .references(() => authUsers.id, { onDelete: 'cascade' }),
    accessToken: text('access_token'),
    refreshToken: text('refresh_token'),
    idToken: text('id_token'),
    password: text('password'),
    accessTokenExpiresAt: timestamp('access_token_expires_at', {
      withTimezone: true,
    }),
    refreshTokenExpiresAt: timestamp('refresh_token_expires_at', {
      withTimezone: true,
    }),
    scope: text('scope'),
    ...timestamps(),
  },
  (t) => [
    unique('auth_account_provider_account_unique').on(
      t.providerId,
      t.accountId,
    ),
  ],
)
export const authVerifications = pgTable(
  'auth_verification',
  {
    id: id(),
    identifier: text('identifier').notNull(),
    value: text('value').notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    ...timestamps(),
  },
  (t) => [index('auth_verification_identifier_idx').on(t.identifier)],
)
export const authTwoFactor = pgTable('auth_two_factor', {
  id: id(),
  userId: uuid('user_id')
    .notNull()
    .unique()
    .references(() => authUsers.id, { onDelete: 'cascade' }),
  secret: text('secret').notNull(),
  backupCodes: text('backup_codes').notNull(),
  verified: boolean('verified').notNull().default(true),
  failedVerificationCount: integer('failed_verification_count')
    .notNull()
    .default(0),
  lockedUntil: timestamp('locked_until', { withTimezone: true }),
  ...timestamps(),
})

export const schools = pgTable('schools', {
  id: id(),
  loginCode: text('login_code').notNull().unique(),
  name: text('name').notNull(),
  shortName: text('short_name').notNull(),
  status: text('status').notNull().default('active'),
  timezone: text('timezone').notNull().default('Asia/Kolkata'),
  board: text('board'),
  affiliationNumber: text('affiliation_number'),
  udiseCode: text('udise_code'),
  address: jsonb('address').notNull(),
  phone: text('phone'),
  email: text('email'),
  website: text('website'),
  principalName: text('principal_name'),
  establishedYear: integer('established_year'),
  logoUrl: text('logo_url'),
  /** The logo in the private document store. Server state, never returned. */
  logoStorageKey: text('logo_storage_key'),
  logoContentType: text('logo_content_type'),
  logoUpdatedAt: timestamp('logo_updated_at', { withTimezone: true }),
  accessVersion: integer('access_version').notNull().default(1),
  // The edit counter of the profile. access_version belongs to the access
  // locking protocol and never doubles as this.
  version: integer('version').notNull().default(1),
  currentAcademicYearId: uuid('current_academic_year_id'),
  ...timestamps(),
})
export const schoolMemberships = pgTable(
  'school_memberships',
  {
    id: id(),
    schoolId: tenant().references(() => schools.id, { onDelete: 'restrict' }),
    userId: uuid('user_id')
      .notNull()
      .references(() => authUsers.id, { onDelete: 'restrict' }),
    kind: membershipKind('kind').notNull(),
    status: membershipStatus('status').notNull().default('active'),
    version: integer('version').notNull().default(1),
    accessVersion: integer('access_version').notNull().default(1),
    ...timestamps(),
  },
  (t) => [
    unique('school_membership_school_user_unique').on(t.schoolId, t.userId),
    unique('school_membership_school_id_unique').on(t.schoolId, t.id),
    index('school_membership_school_user_idx').on(t.schoolId, t.userId),
  ],
)
export const roles = pgTable(
  'roles',
  {
    id: id(),
    schoolId: tenant().references(() => schools.id, { onDelete: 'cascade' }),
    key: text('key').notNull(),
    name: text('name').notNull(),
    isSystem: boolean('is_system').notNull().default(false),
    version: integer('version').notNull().default(1),
    ...timestamps(),
  },
  (t) => [
    unique('roles_school_key_unique').on(t.schoolId, t.key),
    unique('roles_school_id_unique').on(t.schoolId, t.id),
  ],
)
export const rolePermissions = pgTable(
  'role_permissions',
  {
    schoolId: tenant(),
    roleId: uuid('role_id').notNull(),
    permission: text('permission').notNull(),
    scope: text('scope').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.schoolId, t.roleId, t.permission, t.scope] }),
    index('role_permissions_school_role_idx').on(t.schoolId, t.roleId),
  ],
)
export const membershipRoles = pgTable(
  'membership_roles',
  {
    schoolId: tenant(),
    membershipId: uuid('membership_id').notNull(),
    roleId: uuid('role_id').notNull(),
    assignedByMembershipId: uuid('assigned_by_membership_id'),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.schoolId, t.membershipId, t.roleId] })],
)

export const academicYears = pgTable(
  'academic_years',
  {
    id: id(),
    schoolId: tenant(),
    name: text('name').notNull(),
    startDate: date('start_date').notNull(),
    endDate: date('end_date').notNull(),
    status: text('status').notNull(),
    version: integer('version').notNull().default(1),
    ...timestamps(),
  },
  (t) => [
    unique('academic_years_school_id_unique').on(t.schoolId, t.id),
    unique('academic_years_school_name_unique').on(t.schoolId, t.name),
  ],
)
export const grades = pgTable(
  'grades',
  {
    id: id(),
    schoolId: tenant(),
    name: text('name').notNull(),
    shortName: text('short_name').notNull(),
    sortOrder: integer('sort_order').notNull(),
    stream: text('stream'),
    /** Class 1 to 12; null for Nursery, LKG and UKG. Pupils in 9 to 12 get a login. */
    level: smallint('level'),
    version: integer('version').notNull().default(1),
    ...timestamps(),
  },
  (t) => [
    unique('grades_school_id_unique').on(t.schoolId, t.id),
    unique('grades_school_name_unique').on(t.schoolId, t.name),
  ],
)
export const staff = pgTable(
  'staff',
  {
    id: id(),
    schoolId: tenant(),
    employeeCode: text('employee_code').notNull(),
    firstName: text('first_name').notNull(),
    lastName: text('last_name'),
    staffType: text('staff_type').notNull(),
    designation: text('designation').notNull(),
    status: text('status').notNull(),
    gender: text('gender'),
    dateOfBirth: date('date_of_birth'),
    bloodGroup: text('blood_group'),
    phone: text('phone'),
    email: text('email'),
    address: jsonb('address'),
    department: text('department'),
    employmentType: text('employment_type'),
    joiningDate: date('joining_date'),
    leavingDate: date('leaving_date'),
    qualification: text('qualification'),
    experienceYears: numeric('experience_years'),
    monthlySalary: numeric('monthly_salary'),
    bankAccountLast4: text('bank_account_last4'),
    panLast4: text('pan_last4'),
    /** The photograph in the private document store; never a public URL. */
    photoStorageKey: text('photo_storage_key'),
    photoContentType: text('photo_content_type'),
    photoUpdatedAt: timestamp('photo_updated_at', { withTimezone: true }),
    anonymisedAt: timestamp('anonymised_at', { withTimezone: true }),
    version: integer('version').notNull().default(1),
    ...timestamps(),
  },
  (t) => [
    unique('staff_school_id_unique').on(t.schoolId, t.id),
    unique('staff_school_employee_unique').on(t.schoolId, t.employeeCode),
  ],
)
export const sections = pgTable(
  'sections',
  {
    id: id(),
    schoolId: tenant(),
    gradeId: uuid('grade_id').notNull(),
    academicYearId: uuid('academic_year_id').notNull(),
    name: text('name').notNull(),
    classTeacherStaffId: uuid('class_teacher_staff_id'),
    roomNumber: text('room_number'),
    capacity: integer('capacity'),
    version: integer('version').notNull().default(1),
    ...timestamps(),
  },
  (t) => [
    unique('sections_school_id_unique').on(t.schoolId, t.id),
    unique('sections_school_year_grade_name_unique').on(
      t.schoolId,
      t.academicYearId,
      t.gradeId,
      t.name,
    ),
  ],
)
export const subjects = pgTable(
  'subjects',
  {
    id: id(),
    schoolId: tenant(),
    name: text('name').notNull(),
    code: text('code').notNull(),
    type: text('type').notNull(),
    version: integer('version').notNull().default(1),
    ...timestamps(),
  },
  (t) => [
    unique('subjects_school_id_unique').on(t.schoolId, t.id),
    unique('subjects_school_code_unique').on(t.schoolId, t.code),
  ],
)
export const gradeSubjects = pgTable(
  'grade_subjects',
  {
    schoolId: tenant(),
    gradeId: uuid('grade_id').notNull(),
    academicYearId: uuid('academic_year_id').notNull(),
    subjectId: uuid('subject_id').notNull(),
    isOptional: boolean('is_optional').notNull().default(false),
  },
  (t) => [
    primaryKey({
      columns: [t.schoolId, t.gradeId, t.academicYearId, t.subjectId],
    }),
  ],
)
export const holidays = pgTable(
  'holidays',
  {
    id: id(),
    schoolId: tenant(),
    academicYearId: uuid('academic_year_id').notNull(),
    name: text('name').notNull(),
    startDate: date('start_date').notNull(),
    endDate: date('end_date').notNull(),
    type: text('type').notNull(),
    version: integer('version').notNull().default(1),
    ...timestamps(),
  },
  (t) => [unique('holidays_school_id_unique').on(t.schoolId, t.id)],
)
export const students = pgTable(
  'students',
  {
    id: id(),
    schoolId: tenant(),
    admissionNumber: text('admission_number').notNull(),
    firstName: text('first_name').notNull(),
    lastName: text('last_name'),
    status: text('status').notNull(),
    dateOfBirth: date('date_of_birth'),
    gender: text('gender'),
    bloodGroup: text('blood_group'),
    category: text('category'),
    religion: text('religion'),
    motherTongue: text('mother_tongue'),
    nationality: text('nationality'),
    aadhaarLast4: text('aadhaar_last4'),
    /** The Aadhaar number sealed by the API, like the APAAR id below. */
    aadhaarCiphertext: text('aadhaar_ciphertext'),
    /** Last four digits of the APAAR id: all a screen is ever shown. */
    apaarLast4: text('apaar_last4'),
    /** The APAAR id sealed by the API; the key never reaches the database. */
    apaarCiphertext: text('apaar_ciphertext'),
    address: jsonb('address'),
    admissionDate: date('admission_date'),
    admissionType: text('admission_type'),
    previousSchool: text('previous_school'),
    leftOn: date('left_on'),
    leftReason: text('left_reason'),
    house: text('house'),
    /** The photograph in the private document store; never a public URL. */
    photoStorageKey: text('photo_storage_key'),
    photoContentType: text('photo_content_type'),
    photoUpdatedAt: timestamp('photo_updated_at', { withTimezone: true }),
    medicalNotes: text('medical_notes'),
    usesTransport: boolean('uses_transport').notNull().default(false),
    anonymisedAt: timestamp('anonymised_at', { withTimezone: true }),
    version: integer('version').notNull().default(1),
    ...timestamps(),
  },
  (t) => [
    unique('students_school_id_unique').on(t.schoolId, t.id),
    unique('students_school_admission_unique').on(
      t.schoolId,
      t.admissionNumber,
    ),
    index('students_school_status_idx').on(t.schoolId, t.status),
  ],
)
export const guardians = pgTable(
  'guardians',
  {
    id: id(),
    schoolId: tenant(),
    firstName: text('first_name').notNull(),
    lastName: text('last_name'),
    phone: text('phone'),
    altPhone: text('alt_phone'),
    email: text('email'),
    occupation: text('occupation'),
    qualification: text('qualification'),
    annualIncome: numeric('annual_income'),
    address: jsonb('address'),
    officeAddress: jsonb('office_address'),
    /** PAN and Aadhaar sealed by the API, with the digits a screen may show. */
    panCiphertext: text('pan_ciphertext'),
    panLast4: text('pan_last4'),
    aadhaarCiphertext: text('aadhaar_ciphertext'),
    aadhaarLast4: text('aadhaar_last4'),
    anonymisedAt: timestamp('anonymised_at', { withTimezone: true }),
    version: integer('version').notNull().default(1),
    ...timestamps(),
  },
  (t) => [unique('guardians_school_id_unique').on(t.schoolId, t.id)],
)
export const enrollments = pgTable(
  'enrollments',
  {
    id: id(),
    schoolId: tenant(),
    studentId: uuid('student_id').notNull(),
    academicYearId: uuid('academic_year_id').notNull(),
    sectionId: uuid('section_id').notNull(),
    rollNumber: integer('roll_number'),
    joinedOn: date('joined_on').notNull(),
    leftOn: date('left_on'),
    outcome: text('outcome').notNull().default('ongoing'),
    ...timestamps(),
  },
  (t) => [
    unique('enrollments_school_id_unique').on(t.schoolId, t.id),
    index('enrollments_school_student_idx').on(t.schoolId, t.studentId),
    index('enrollments_school_section_idx').on(t.schoolId, t.sectionId),
  ],
)
export const studentGuardians = pgTable(
  'student_guardians',
  {
    schoolId: tenant(),
    studentId: uuid('student_id').notNull(),
    guardianId: uuid('guardian_id').notNull(),
    relation: text('relation').notNull(),
    isPrimary: boolean('is_primary').notNull().default(false),
    receivesNotifications: boolean('receives_notifications')
      .notNull()
      .default(true),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.schoolId, t.studentId, t.guardianId] })],
)
export const studentDocuments = pgTable(
  'student_documents',
  {
    id: id(),
    schoolId: tenant(),
    studentId: uuid('student_id').notNull(),
    documentType: text('document_type').notNull(),
    fileName: text('file_name').notNull(),
    storageKey: text('storage_key').notNull(),
    sizeBytes: bigint('size_bytes', { mode: 'number' }).notNull(),
    uploadedByMembershipId: uuid('uploaded_by_membership_id'),
    verified: boolean('verified').notNull().default(false),
    ...timestamps(),
  },
  (t) => [unique('student_documents_school_id_unique').on(t.schoolId, t.id)],
)
export const teachingAssignments = pgTable(
  'teaching_assignments',
  {
    id: id(),
    schoolId: tenant(),
    staffId: uuid('staff_id').notNull(),
    academicYearId: uuid('academic_year_id').notNull(),
    sectionId: uuid('section_id').notNull(),
    subjectId: uuid('subject_id').notNull(),
    effectiveFrom: date('effective_from').notNull(),
    effectiveTo: date('effective_to'),
    ...timestamps(),
  },
  (t) => [
    index('teaching_assignments_scope_idx').on(
      t.schoolId,
      t.staffId,
      t.academicYearId,
      t.sectionId,
      t.subjectId,
    ),
  ],
)
export const bellSchedules = pgTable(
  'bell_schedules',
  {
    id: id(),
    schoolId: tenant(),
    academicYearId: uuid('academic_year_id').notNull(),
    name: text('name').notNull(),
    gradeIds: uuid('grade_ids').array().notNull(),
    workingDays: smallint('working_days').array().notNull(),
    periods: jsonb('periods').notNull(),
    saturdayPeriodCount: integer('saturday_period_count'),
    version: integer('version').notNull().default(1),
    ...timestamps(),
  },
  (t) => [unique('bell_schedules_school_id_unique').on(t.schoolId, t.id)],
)
export const timetableEntries = pgTable(
  'timetable_entries',
  {
    id: id(),
    schoolId: tenant(),
    academicYearId: uuid('academic_year_id').notNull(),
    sectionId: uuid('section_id').notNull(),
    dayOfWeek: smallint('day_of_week').notNull(),
    periodIndex: integer('period_index').notNull(),
    subjectId: uuid('subject_id').notNull(),
    staffId: uuid('staff_id'),
    roomNumber: text('room_number'),
    ...timestamps(),
  },
  (t) => [
    unique('timetable_entries_slot_unique').on(
      t.schoolId,
      t.academicYearId,
      t.sectionId,
      t.dayOfWeek,
      t.periodIndex,
    ),
  ],
)
export const bellScheduleGrades = pgTable(
  'bell_schedule_grades',
  {
    schoolId: tenant(),
    bellScheduleId: uuid('bell_schedule_id').notNull(),
    gradeId: uuid('grade_id').notNull(),
  },
  (t) => [primaryKey({ columns: [t.schoolId, t.bellScheduleId, t.gradeId] })],
)
export const substitutions = pgTable('substitutions', {
  id: id(),
  schoolId: tenant(),
  date: date('date').notNull(),
  sectionId: uuid('section_id').notNull(),
  periodIndex: integer('period_index').notNull(),
  subjectId: uuid('subject_id').notNull(),
  absentStaffId: uuid('absent_staff_id').notNull(),
  substituteStaffId: uuid('substitute_staff_id'),
  reason: text('reason'),
  notified: boolean('notified').notNull().default(false),
  ...timestamps(),
})
export const membershipStaffLinks = pgTable(
  'membership_staff_links',
  {
    schoolId: tenant(),
    membershipId: uuid('membership_id').notNull(),
    staffId: uuid('staff_id').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.schoolId, t.membershipId] }),
    unique('membership_staff_links_school_staff_unique').on(
      t.schoolId,
      t.staffId,
    ),
  ],
)
export const membershipGuardianLinks = pgTable(
  'membership_guardian_links',
  {
    schoolId: tenant(),
    membershipId: uuid('membership_id').notNull(),
    guardianId: uuid('guardian_id').notNull(),
    verifiedAt: timestamp('verified_at', { withTimezone: true }).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.schoolId, t.membershipId] }),
    unique('membership_guardian_links_school_guardian_unique').on(
      t.schoolId,
      t.guardianId,
    ),
  ],
)
export const guardianStudentAccess = pgTable(
  'guardian_student_access',
  {
    schoolId: tenant(),
    guardianId: uuid('guardian_id').notNull(),
    studentId: uuid('student_id').notNull(),
    status: text('status').notNull(),
    areas: text('areas').array().notNull(),
    approvedByMembershipId: uuid('approved_by_membership_id').notNull(),
    approvedAt: timestamp('approved_at', { withTimezone: true }).notNull(),
    revokedAt: timestamp('revoked_at', { withTimezone: true }),
  },
  (t) => [primaryKey({ columns: [t.schoolId, t.guardianId, t.studentId] })],
)
export const membershipStudentLinks = pgTable(
  'membership_student_links',
  {
    schoolId: tenant(),
    membershipId: uuid('membership_id').notNull(),
    studentId: uuid('student_id').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.schoolId, t.membershipId] }),
    unique('membership_student_links_school_student_unique').on(
      t.schoolId,
      t.studentId,
    ),
  ],
)
export const invitations = pgTable(
  'school_invitations',
  {
    id: id(),
    schoolId: tenant(),
    identifierType: text('identifier_type').notNull(),
    identifierNormalized: text('identifier_normalized').notNull(),
    destinationMasked: text('destination_masked').notNull(),
    tokenDigest: text('token_digest').notNull().unique(),
    status: invitationStatus('status').notNull().default('pending'),
    proposedRoleKeys: text('proposed_role_keys').array().notNull(),
    displayName: text('display_name').notNull(),
    staffId: uuid('staff_id'),
    inviterMembershipId: uuid('inviter_membership_id').notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    acceptedAt: timestamp('accepted_at', { withTimezone: true }),
    version: integer('version').notNull().default(1),
    ...timestamps(),
  },
  (t) => [
    index('invitations_school_pending_idx').on(
      t.schoolId,
      t.status,
      t.expiresAt,
    ),
  ],
)
export const resourceAccessRules = pgTable(
  'resource_access_rules',
  {
    id: id(),
    schoolId: tenant(),
    membershipId: uuid('membership_id').notNull(),
    permission: text('permission').notNull(),
    effect: accessEffect('effect').notNull(),
    targetType: text('target_type').notNull(),
    academicYearId: uuid('academic_year_id'),
    sectionId: uuid('section_id'),
    studentId: uuid('student_id'),
    staffId: uuid('staff_id'),
    documentId: uuid('document_id'),
    effectiveFrom: timestamp('effective_from', {
      withTimezone: true,
    }).notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    revokedAt: timestamp('revoked_at', { withTimezone: true }),
    reason: text('reason').notNull(),
    authorMembershipId: uuid('author_membership_id').notNull(),
    version: integer('version').notNull().default(1),
    ...timestamps(),
  },
  (t) => [
    index('access_rules_decision_idx').on(
      t.schoolId,
      t.membershipId,
      t.permission,
      t.expiresAt,
    ),
  ],
)
export const auditEvents = pgTable(
  'audit_events',
  {
    id: id(),
    schoolId: tenant(),
    actorUserId: uuid('actor_user_id'),
    actorMembershipId: uuid('actor_membership_id'),
    action: text('action').notNull(),
    targetType: text('target_type').notNull(),
    targetId: uuid('target_id'),
    result: text('result').notNull(),
    summary: text('summary').notNull(),
    safeChanges: jsonb('safe_changes')
      .notNull()
      .default(sql`'{}'::jsonb`),
    requestId: text('request_id').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [index('audit_events_school_created_idx').on(t.schoolId, t.createdAt)],
)
export const deliveryOutbox = pgTable(
  'delivery_outbox',
  {
    id: id(),
    schoolId: tenant(),
    eventType: text('event_type').notNull(),
    destination: text('destination').notNull(),
    payload: jsonb('payload').notNull(),
    status: deliveryStatus('status').notNull().default('queued'),
    attempts: integer('attempts').notNull().default(0),
    availableAt: timestamp('available_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    lockedAt: timestamp('locked_at', { withTimezone: true }),
    deliveredAt: timestamp('delivered_at', { withTimezone: true }),
    lastError: text('last_error'),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [index('delivery_outbox_ready_idx').on(t.status, t.availableAt)],
)

/**
 * Task 5 working tables. Both hold work in progress that expires, not school
 * records: the staged import keeps only server-validated rows, and the export
 * job keeps the permission and access version it was requested under.
 */
export const studentImportPreviews = pgTable(
  'student_import_previews',
  {
    id: id(),
    schoolId: tenant(),
    createdByMembershipId: uuid('created_by_membership_id').notNull(),
    academicYearId: uuid('academic_year_id').notNull(),
    status: text('status').notNull(),
    totalRows: integer('total_rows').notNull(),
    validRows: integer('valid_rows').notNull(),
    rows: jsonb('rows').notNull(),
    errors: jsonb('errors')
      .notNull()
      .default(sql`'[]'::jsonb`),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    version: integer('version').notNull().default(1),
    ...timestamps(),
  },
  (t) => [
    unique('student_import_previews_school_id_unique').on(t.schoolId, t.id),
    index('student_import_previews_expiry_idx').on(t.schoolId, t.expiresAt),
  ],
)
export const exportJobs = pgTable(
  'export_jobs',
  {
    id: id(),
    schoolId: tenant(),
    requestedByMembershipId: uuid('requested_by_membership_id').notNull(),
    kind: text('kind').notNull(),
    status: text('status').notNull(),
    accessVersion: integer('access_version').notNull(),
    permission: text('permission').notNull(),
    criteria: jsonb('criteria')
      .notNull()
      .default(sql`'{}'::jsonb`),
    rowCount: integer('row_count'),
    storageKey: text('storage_key'),
    /** The name the file is delivered under, set when it becomes ready. */
    fileName: text('file_name'),
    /** The type the download route puts on the response. */
    contentType: text('content_type'),
    /** The assurance the request that asked for the file had reached. */
    requestedAssurance: text('requested_assurance'),
    /** When that request's second factor was checked, if it had one. */
    requestedMfaVerifiedAt: timestamp('requested_mfa_verified_at', { withTimezone: true }),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    ...timestamps(),
  },
  (t) => [
    unique('export_jobs_school_id_unique').on(t.schoolId, t.id),
    index('export_jobs_requester_idx').on(t.schoolId, t.requestedByMembershipId, t.createdAt),
  ],
)

export const numberSequences = pgTable(
  'number_sequences',
  {
    schoolId: tenant(),
    /** 'admission', 'employee' or 'receipt'. */
    kind: text('kind').notNull(),
    /** The academic year id for admissions and receipts, empty for employee codes. */
    period: text('period').notNull().default(''),
    nextValue: integer('next_value').notNull().default(1),
    ...timestamps(),
  },
  (t) => [primaryKey({ columns: [t.schoolId, t.kind, t.period] })],
)

/**
 * Task 12 lifecycle tables. A consent row is an event: the newest row for a
 * (guardian, purpose) pair is the current answer, and a trigger refuses any
 * edit. A note keeps the words somebody typed out of the append-only audit
 * row, so it can be redacted without rewriting history.
 */
export const guardianConsents = pgTable(
  'guardian_consents',
  {
    id: id(),
    schoolId: tenant(),
    studentId: uuid('student_id').notNull(),
    guardianId: uuid('guardian_id').notNull(),
    purpose: text('purpose').notNull(),
    status: text('status').notNull(),
    method: text('method').notNull(),
    recordedByMembershipId: uuid('recorded_by_membership_id').notNull(),
    evidenceReference: text('evidence_reference'),
    recordedAt: timestamp('recorded_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    unique('guardian_consents_school_id_unique').on(t.schoolId, t.id),
    index('guardian_consents_current_idx').on(
      t.schoolId,
      t.studentId,
      t.guardianId,
      t.purpose,
      t.recordedAt,
    ),
  ],
)

export const auditEventNotes = pgTable(
  'audit_event_notes',
  {
    id: id(),
    schoolId: tenant(),
    auditEventId: uuid('audit_event_id').notNull().unique(),
    note: text('note').notNull(),
    redactedAt: timestamp('redacted_at', { withTimezone: true }),
    redactedByMembershipId: uuid('redacted_by_membership_id'),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [unique('audit_event_notes_school_id_unique').on(t.schoolId, t.id)],
)

/**
 * Task 19 fee tables. Money is integer paise in a bigint. The two ledger
 * tables are append-only: a trigger refuses every edit except clearing
 * payer_name, which is what anonymising a pupil needs.
 */
const version = () => integer('version').notNull().default(1)
const paise = (name: string) => bigint(name, { mode: 'number' })

export const feeHeads = pgTable(
  'fee_heads',
  {
    id: id(),
    schoolId: tenant(),
    name: text('name').notNull(),
    category: text('category').notNull(),
    /** 'class' for everybody in a class, 'opt_in' for pupils who take it. */
    appliesTo: text('applies_to').notNull(),
    frequency: text('frequency').notNull(),
    active: boolean('active').notNull().default(true),
    version: version(),
    ...timestamps(),
  },
  (t) => [unique('fee_heads_school_id_id_key').on(t.schoolId, t.id)],
)

export const feeStructures = pgTable(
  'fee_structures',
  {
    id: id(),
    schoolId: tenant(),
    academicYearId: uuid('academic_year_id').notNull(),
    feeHeadId: uuid('fee_head_id').notNull(),
    /** Null means every class. */
    gradeId: uuid('grade_id'),
    /** Per instalment. */
    amountPaise: paise('amount_paise').notNull(),
    version: version(),
    ...timestamps(),
  },
  (t) => [unique('fee_structures_school_id_id_key').on(t.schoolId, t.id)],
)

export const feeStudentHeads = pgTable(
  'fee_student_heads',
  {
    id: id(),
    schoolId: tenant(),
    studentId: uuid('student_id').notNull(),
    academicYearId: uuid('academic_year_id').notNull(),
    feeHeadId: uuid('fee_head_id').notNull(),
    /** This pupil's own amount per instalment; null takes the structure's. */
    amountPaise: paise('amount_paise'),
    startsOn: date('starts_on').notNull(),
    endsOn: date('ends_on'),
    version: version(),
    ...timestamps(),
  },
  (t) => [unique('fee_student_heads_school_id_id_key').on(t.schoolId, t.id)],
)

export const feeConcessions = pgTable(
  'fee_concessions',
  {
    id: id(),
    schoolId: tenant(),
    studentId: uuid('student_id').notNull(),
    academicYearId: uuid('academic_year_id').notNull(),
    /** Null means every head. */
    feeHeadId: uuid('fee_head_id'),
    category: text('category').notNull(),
    kind: text('kind').notNull(),
    /** Basis points, for a percent concession. */
    percentBp: integer('percent_bp'),
    /** Per instalment, for an amount concession. */
    amountPaise: paise('amount_paise'),
    version: version(),
    ...timestamps(),
  },
  (t) => [unique('fee_concessions_school_id_id_key').on(t.schoolId, t.id)],
)

export const feeReceipts = pgTable(
  'fee_receipts',
  {
    id: id(),
    schoolId: tenant(),
    studentId: uuid('student_id').notNull(),
    academicYearId: uuid('academic_year_id').notNull(),
    kind: text('kind').notNull(),
    receiptNumber: text('receipt_number').notNull(),
    amountPaise: paise('amount_paise').notNull(),
    mode: text('mode'),
    reference: text('reference'),
    receivedOn: date('received_on').notNull(),
    payerName: text('payer_name'),
    reversesReceiptId: uuid('reverses_receipt_id'),
    recordedByMembershipId: uuid('recorded_by_membership_id').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    unique('fee_receipts_school_id_id_key').on(t.schoolId, t.id),
    unique('fee_receipts_school_id_receipt_number_key').on(t.schoolId, t.receiptNumber),
    index('fee_receipts_student_idx').on(t.schoolId, t.studentId, t.academicYearId),
    index('fee_receipts_received_idx').on(t.schoolId, t.receivedOn),
  ],
)

export const feeReceiptLines = pgTable(
  'fee_receipt_lines',
  {
    id: id(),
    schoolId: tenant(),
    receiptId: uuid('receipt_id').notNull(),
    feeHeadId: uuid('fee_head_id').notNull(),
    amountPaise: paise('amount_paise').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    unique('fee_receipt_lines_school_id_id_key').on(t.schoolId, t.id),
    unique('fee_receipt_lines_school_id_receipt_id_fee_head_id_key').on(
      t.schoolId,
      t.receiptId,
      t.feeHeadId,
    ),
  ],
)

/**
 * Task 20 attendance tables. Every row is an event: the current mark for a
 * pupil or a staff member on a date is the row with the highest revision, a
 * later save or a correction is a new row pointing at the one it supersedes,
 * and a trigger refuses every edit and delete.
 */
export const attendanceEntries = pgTable(
  'attendance_entries',
  {
    id: id(),
    schoolId: tenant(),
    studentId: uuid('student_id').notNull(),
    sectionId: uuid('section_id').notNull(),
    academicYearId: uuid('academic_year_id').notNull(),
    date: date('date').notNull(),
    /** present, absent, late, leave or half_day. */
    mark: text('mark').notNull(),
    /** 1 for the first mark on a date, then one more per superseding row. */
    revision: integer('revision').notNull(),
    supersedesEntryId: uuid('supersedes_entry_id'),
    /** 'marking' by whoever marks the register, 'correction' by the office with a reason. */
    kind: text('kind').notNull(),
    recordedByMembershipId: uuid('recorded_by_membership_id').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    unique('attendance_entries_school_id_id_key').on(t.schoolId, t.id),
    unique('attendance_entries_school_id_student_id_date_revision_key').on(
      t.schoolId,
      t.studentId,
      t.date,
      t.revision,
    ),
    index('attendance_entries_section_date_idx').on(t.schoolId, t.sectionId, t.date),
    index('attendance_entries_student_date_idx').on(t.schoolId, t.studentId, t.date),
  ],
)

export const staffAttendanceEntries = pgTable(
  'staff_attendance_entries',
  {
    id: id(),
    schoolId: tenant(),
    staffId: uuid('staff_id').notNull(),
    date: date('date').notNull(),
    mark: text('mark').notNull(),
    revision: integer('revision').notNull(),
    supersedesEntryId: uuid('supersedes_entry_id'),
    kind: text('kind').notNull(),
    recordedByMembershipId: uuid('recorded_by_membership_id').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    unique('staff_attendance_entries_school_id_id_key').on(t.schoolId, t.id),
    unique('staff_attendance_entries_school_id_staff_id_date_revision_key').on(
      t.schoolId,
      t.staffId,
      t.date,
      t.revision,
    ),
    index('staff_attendance_entries_date_idx').on(t.schoolId, t.date),
    index('staff_attendance_entries_staff_date_idx').on(t.schoolId, t.staffId, t.date),
  ],
)

/**
 * Task 21. One row per academic year and exam of the fixed CBSE pattern; the
 * pattern itself (components and maximums) is a constant in @erp/contracts.
 */
export const exams = pgTable(
  'exams',
  {
    id: id(),
    schoolId: tenant(),
    academicYearId: uuid('academic_year_id').notNull(),
    /** periodic_test_1, half_yearly, periodic_test_2 or annual. */
    kind: text('kind').notNull(),
    startsOn: date('starts_on').notNull(),
    endsOn: date('ends_on').notNull(),
    /** The last day a subject teacher may change a mark, in the school's timezone. */
    recheckDeadline: date('recheck_deadline').notNull(),
    version: integer('version').notNull().default(1),
    ...timestamps(),
  },
  (t) => [
    unique('exams_school_id_id_key').on(t.schoolId, t.id),
    unique('exams_school_id_academic_year_id_id_key').on(t.schoolId, t.academicYearId, t.id),
    unique('exams_school_id_academic_year_id_kind_key').on(t.schoolId, t.academicYearId, t.kind),
  ],
)

/** One sheet of marks: an exam, a section and a subject. */
export const examPapers = pgTable(
  'exam_papers',
  {
    id: id(),
    schoolId: tenant(),
    examId: uuid('exam_id').notNull(),
    academicYearId: uuid('academic_year_id').notNull(),
    sectionId: uuid('section_id').notNull(),
    subjectId: uuid('subject_id').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    unique('exam_papers_school_id_id_key').on(t.schoolId, t.id),
    unique('exam_papers_school_id_exam_id_section_id_subject_id_key').on(
      t.schoolId,
      t.examId,
      t.sectionId,
      t.subjectId,
    ),
    index('exam_papers_section_idx').on(t.schoolId, t.sectionId),
  ],
)

/**
 * One mark, appended. The current mark of a pupil, paper and component is the
 * highest revision; nothing is ever updated or deleted.
 */
export const examMarks = pgTable(
  'exam_marks',
  {
    id: id(),
    schoolId: tenant(),
    paperId: uuid('paper_id').notNull(),
    examId: uuid('exam_id').notNull(),
    academicYearId: uuid('academic_year_id').notNull(),
    sectionId: uuid('section_id').notNull(),
    subjectId: uuid('subject_id').notNull(),
    studentId: uuid('student_id').notNull(),
    /** periodic_test, notebook, subject_enrichment or written. */
    component: text('component').notNull(),
    /** marked, absent, medical or exempt. */
    status: text('status').notNull(),
    /** Whole tenths of a mark, set only when the status is marked. */
    marksTenths: integer('marks_tenths'),
    revision: integer('revision').notNull(),
    supersedesMarkId: uuid('supersedes_mark_id'),
    /** 'entry' from the marks sheet, 'correction' by the office with a reason. */
    kind: text('kind').notNull(),
    /** recheck, entry_error or other; the words are the audit note. */
    reasonKind: text('reason_kind'),
    recordedByMembershipId: uuid('recorded_by_membership_id').notNull(),
    recordedAt: timestamp('recorded_at', { withTimezone: true })
      .notNull()
      .default(sql`clock_timestamp()`),
  },
  (t) => [
    unique('exam_marks_school_id_id_key').on(t.schoolId, t.id),
    unique('exam_marks_school_id_paper_id_student_id_component_revision_key').on(
      t.schoolId,
      t.paperId,
      t.studentId,
      t.component,
      t.revision,
    ),
    index('exam_marks_student_idx').on(t.schoolId, t.studentId),
    index('exam_marks_exam_section_idx').on(t.schoolId, t.examId, t.sectionId),
  ],
)

/** The office publishing one exam's results for one section; appended, never changed. */
export const examPublications = pgTable(
  'exam_publications',
  {
    id: id(),
    schoolId: tenant(),
    examId: uuid('exam_id').notNull(),
    academicYearId: uuid('academic_year_id').notNull(),
    sectionId: uuid('section_id').notNull(),
    publishedByMembershipId: uuid('published_by_membership_id').notNull(),
    publishedAt: timestamp('published_at', { withTimezone: true })
      .notNull()
      .default(sql`clock_timestamp()`),
  },
  (t) => [unique('exam_publications_school_id_id_key').on(t.schoolId, t.id)],
)

/** The class teacher's co-scholastic grades and remarks for one pupil and term. */
export const reportCardEntries = pgTable(
  'report_card_entries',
  {
    id: id(),
    schoolId: tenant(),
    studentId: uuid('student_id').notNull(),
    academicYearId: uuid('academic_year_id').notNull(),
    sectionId: uuid('section_id').notNull(),
    /** term_1 or term_2. */
    term: text('term').notNull(),
    workEducation: text('work_education'),
    artEducation: text('art_education'),
    healthPhysicalEducation: text('health_physical_education'),
    discipline: text('discipline'),
    /** Free text about a child; cleared by anonymisation, never in an audit row. */
    remarks: text('remarks'),
    updatedByMembershipId: uuid('updated_by_membership_id').notNull(),
    version: integer('version').notNull().default(1),
    ...timestamps(),
  },
  (t) => [
    unique('report_card_entries_school_id_id_key').on(t.schoolId, t.id),
    unique('report_card_entries_school_id_section_id_student_id_term_key').on(
      t.schoolId,
      t.sectionId,
      t.studentId,
      t.term,
    ),
  ],
)

/** A published report card, frozen. Only the remarks can ever be cleared. */
export const reportCardVersions = pgTable(
  'report_card_versions',
  {
    id: id(),
    schoolId: tenant(),
    studentId: uuid('student_id').notNull(),
    academicYearId: uuid('academic_year_id').notNull(),
    sectionId: uuid('section_id').notNull(),
    /** term_1 or final. */
    card: text('card').notNull(),
    versionNumber: integer('version_number').notNull(),
    content: jsonb('content').notNull(),
    remarks: jsonb('remarks'),
    contentHash: text('content_hash').notNull(),
    publishedByMembershipId: uuid('published_by_membership_id').notNull(),
    publishedAt: timestamp('published_at', { withTimezone: true })
      .notNull()
      .default(sql`clock_timestamp()`),
  },
  (t) => [
    unique('report_card_versions_school_id_id_key').on(t.schoolId, t.id),
    unique('report_card_versions_school_id_student_id_academic_year_id_card_version_number_key').on(
      t.schoolId,
      t.studentId,
      t.academicYearId,
      t.card,
      t.versionNumber,
    ),
    index('report_card_versions_section_idx').on(t.schoolId, t.sectionId, t.card),
  ],
)

/** The school's grade bands, marks-or-grades choice and report card layout. */
export const examSettings = pgTable(
  'exam_settings',
  {
    id: id(),
    schoolId: tenant().unique(),
    /** marks or grades. */
    displayMode: text('display_mode').notNull(),
    gradeBands: jsonb('grade_bands').notNull(),
    layout: jsonb('layout').notNull(),
    updatedByMembershipId: uuid('updated_by_membership_id').notNull(),
    version: integer('version').notNull().default(1),
    ...timestamps(),
  },
  (t) => [unique('exam_settings_school_id_id_key').on(t.schoolId, t.id)],
)

/**
 * Task 22. One row per school with the automatic message switches; a school
 * without a row has the column defaults.
 */
export const communicationSettings = pgTable('communication_settings', {
  schoolId: tenant().primaryKey(),
  absenceEnabled: boolean('absence_enabled').notNull().default(true),
  absenceDelayMinutes: integer('absence_delay_minutes').notNull().default(30),
  resultsEnabled: boolean('results_enabled').notNull().default(true),
  reportCardsEnabled: boolean('report_cards_enabled').notNull().default(true),
  feeRemindersEnabled: boolean('fee_reminders_enabled').notNull().default(true),
  feeReminderDaysBefore: integer('fee_reminder_days_before').notNull().default(3),
  feeOverdueEveryDays: integer('fee_overdue_every_days').notNull().default(7),
  birthdaysPupilsEnabled: boolean('birthdays_pupils_enabled').notNull().default(true),
  birthdaysStaffEnabled: boolean('birthdays_staff_enabled').notNull().default(true),
  dailySendHour: integer('daily_send_hour').notNull().default(8),
  automaticSince: timestamp('automatic_since', { withTimezone: true }).notNull().defaultNow(),
  version: integer('version').notNull().default(1),
  ...timestamps(),
})

/** The school's own wording for notices and for each automatic message. */
export const messageTemplates = pgTable(
  'message_templates',
  {
    id: id(),
    schoolId: tenant(),
    kind: text('kind').notNull(),
    name: text('name').notNull(),
    title: text('title').notNull(),
    body: text('body').notNull(),
    archivedAt: timestamp('archived_at', { withTimezone: true }),
    createdByMembershipId: uuid('created_by_membership_id').notNull(),
    version: integer('version').notNull().default(1),
    ...timestamps(),
  },
  (t) => [unique('message_templates_school_id_id_key').on(t.schoolId, t.id)],
)

/**
 * One announcement. The words live here once; message_recipients records who
 * it went to. created_by_membership_id is null for the school's automatic
 * messages, which carry a dedupe_key instead.
 */
export const messages = pgTable(
  'messages',
  {
    id: id(),
    schoolId: tenant(),
    kind: text('kind').notNull(),
    audience: text('audience').notNull(),
    /** families, students or both; null for the staff audiences. */
    recipients: text('recipients'),
    gradeId: uuid('grade_id'),
    /** The last class of a grade_range audience; grade_id is the first. */
    gradeToId: uuid('grade_to_id'),
    sectionId: uuid('section_id'),
    academicYearId: uuid('academic_year_id'),
    studentId: uuid('student_id'),
    staffId: uuid('staff_id'),
    title: text('title').notNull(),
    body: text('body').notNull(),
    status: text('status').notNull(),
    sendAt: timestamp('send_at', { withTimezone: true }),
    sentAt: timestamp('sent_at', { withTimezone: true }),
    withdrawnAt: timestamp('withdrawn_at', { withTimezone: true }),
    withdrawnByMembershipId: uuid('withdrawn_by_membership_id'),
    cancelledAt: timestamp('cancelled_at', { withTimezone: true }),
    cancelReason: text('cancel_reason'),
    createdByMembershipId: uuid('created_by_membership_id'),
    templateId: uuid('template_id'),
    dedupeKey: text('dedupe_key'),
    redactedAt: timestamp('redacted_at', { withTimezone: true }),
    version: integer('version').notNull().default(1),
    ...timestamps(),
  },
  (t) => [
    unique('messages_school_id_id_key').on(t.schoolId, t.id),
    unique('messages_school_id_dedupe_key_key').on(t.schoolId, t.dedupeKey),
  ],
)

/** A file sent with a message, as bytes in the private document store. */
export const messageAttachments = pgTable(
  'message_attachments',
  {
    id: id(),
    schoolId: tenant(),
    messageId: uuid('message_id').notNull(),
    fileName: text('file_name').notNull(),
    contentType: text('content_type').notNull(),
    sizeBytes: integer('size_bytes').notNull(),
    storageKey: text('storage_key').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    unique('message_attachments_school_id_id_key').on(t.schoolId, t.id),
    index('message_attachments_message_idx').on(t.schoolId, t.messageId),
  ],
)

/**
 * One person a message was for: a guardian (reached through student_id), a
 * staff member, or a pupil themself (is_student, the pupil in student_id). section_id, academic_year_id and sender_membership_id are
 * copied from the message so the scope terms reach a row without a join.
 */
export const messageRecipients = pgTable(
  'message_recipients',
  {
    id: id(),
    schoolId: tenant(),
    messageId: uuid('message_id').notNull(),
    guardianId: uuid('guardian_id'),
    staffId: uuid('staff_id'),
    isStudent: boolean('is_student').notNull().default(false),
    membershipId: uuid('membership_id'),
    studentId: uuid('student_id'),
    sectionId: uuid('section_id'),
    academicYearId: uuid('academic_year_id'),
    senderMembershipId: uuid('sender_membership_id'),
    /** delivered, no_consent, not_receiving or no_contact. */
    outcome: text('outcome').notNull(),
    inApp: boolean('in_app').notNull(),
    /** none, pending, sent, failed or cancelled. */
    emailStatus: text('email_status').notNull(),
    emailMasked: text('email_masked'),
    emailAttempts: integer('email_attempts').notNull().default(0),
    emailNextAttemptAt: timestamp('email_next_attempt_at', { withTimezone: true }),
    emailSentAt: timestamp('email_sent_at', { withTimezone: true }),
    readAt: timestamp('read_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    unique('message_recipients_school_id_id_key').on(t.schoolId, t.id),
    index('message_recipients_message_idx').on(t.schoolId, t.messageId),
  ],
)

export const schoolTables = [
  schoolMemberships,
  roles,
  rolePermissions,
  membershipRoles,
  academicYears,
  grades,
  staff,
  sections,
  subjects,
  gradeSubjects,
  holidays,
  students,
  guardians,
  enrollments,
  studentGuardians,
  studentDocuments,
  teachingAssignments,
  bellSchedules,
  bellScheduleGrades,
  timetableEntries,
  substitutions,
  membershipStaffLinks,
  membershipGuardianLinks,
  guardianStudentAccess,
  membershipStudentLinks,
  invitations,
  resourceAccessRules,
  auditEvents,
  deliveryOutbox,
  studentImportPreviews,
  exportJobs,
  numberSequences,
  guardianConsents,
  auditEventNotes,
  feeHeads,
  feeStructures,
  feeStudentHeads,
  feeConcessions,
  feeReceipts,
  feeReceiptLines,
  attendanceEntries,
  staffAttendanceEntries,
  exams,
  examPapers,
  examMarks,
  examPublications,
  reportCardEntries,
  reportCardVersions,
  examSettings,
  communicationSettings,
  messageTemplates,
  messages,
  messageAttachments,
  messageRecipients,
] as const
