/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AccessUnavailableRouteImport } from './routes/access-unavailable'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SelectSchoolRouteImport } from './routes/select-school'
import { Route as TestCodesRouteImport } from './routes/test-codes'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AccountChangePasswordRouteImport } from './routes/account/change-password'
import { Route as AccountSecurityRouteImport } from './routes/account/security'
import { Route as MfaSetupRouteImport } from './routes/mfa/setup'
import { Route as MfaVerifyRouteImport } from './routes/mfa/verify'
import { Route as AppAttendanceIndexRouteImport } from './routes/_app/attendance/index'
import { Route as AppExamsIndexRouteImport } from './routes/_app/exams/index'
import { Route as AppExamsExamIdRouteImport } from './routes/_app/exams/$examId'
import { Route as AppFeesIndexRouteImport } from './routes/_app/fees/index'
import { Route as AppFeesCollectionsRouteImport } from './routes/_app/fees/collections'
import { Route as AppFeesSetupRouteImport } from './routes/_app/fees/setup'
import { Route as AppMessagesIndexRouteImport } from './routes/_app/messages/index'
import { Route as AppMessagesNewRouteImport } from './routes/_app/messages/new'
import { Route as AppSettingsAuditLogRouteImport } from './routes/_app/settings/audit-log'
import { Route as AppSettingsRolesRouteImport } from './routes/_app/settings/roles'
import { Route as AppSettingsUsersRouteImport } from './routes/_app/settings/users'
import { Route as AppSetupAcademicYearsRouteImport } from './routes/_app/setup/academic-years'
import { Route as AppSetupClassesRouteImport } from './routes/_app/setup/classes'
import { Route as AppSetupHolidaysRouteImport } from './routes/_app/setup/holidays'
import { Route as AppSetupSchoolRouteImport } from './routes/_app/setup/school'
import { Route as AppSetupSubjectsRouteImport } from './routes/_app/setup/subjects'
import { Route as AppStaffIndexRouteImport } from './routes/_app/staff/index'
import { Route as AppStaffStaffIdRouteImport } from './routes/_app/staff/$staffId'
import { Route as AppStaffNewRouteImport } from './routes/_app/staff/new'
import { Route as AppStudentsIndexRouteImport } from './routes/_app/students/index'
import { Route as AppStudentsStudentIdRouteImport } from './routes/_app/students/$studentId'
import { Route as AppStudentsImportRouteImport } from './routes/_app/students/import'
import { Route as AppStudentsNewRouteImport } from './routes/_app/students/new'
import { Route as AppStudentsPromoteRouteImport } from './routes/_app/students/promote'
import { Route as AppTimetableIndexRouteImport } from './routes/_app/timetable/index'
import { Route as AppTimetablePeriodsRouteImport } from './routes/_app/timetable/periods'
import { Route as AppTimetableSubstitutionsRouteImport } from './routes/_app/timetable/substitutions'
import { Route as AppTimetableTeachersRouteImport } from './routes/_app/timetable/teachers'
import { Route as AppAttendanceStaffIndexRouteImport } from './routes/_app/attendance/staff/index'
import { Route as AppAttendanceStaffStaffIdRouteImport } from './routes/_app/attendance/staff/$staffId'
import { Route as AppAttendanceStaffMonthRouteImport } from './routes/_app/attendance/staff/month'
import { Route as AppAttendanceStudentsStudentIdRouteImport } from './routes/_app/attendance/students/$studentId'
import { Route as AppExamsPapersPaperIdRouteImport } from './routes/_app/exams/papers/$paperId'
import { Route as AppExamsReportCardsIndexRouteImport } from './routes/_app/exams/report-cards/index'
import { Route as AppExamsReportCardsVersionIdRouteImport } from './routes/_app/exams/report-cards/$versionId'
import { Route as AppExamsSettingsIndexRouteImport } from './routes/_app/exams/settings/index'
import { Route as AppExamsStudentsStudentIdRouteImport } from './routes/_app/exams/students/$studentId'
import { Route as AppFeesReceiptsReceiptIdRouteImport } from './routes/_app/fees/receipts/$receiptId'
import { Route as AppFeesStudentsStudentIdRouteImport } from './routes/_app/fees/students/$studentId'
import { Route as AppMessagesMessageIdIndexRouteImport } from './routes/_app/messages/$messageId/index'
import { Route as AppMessagesMessageIdEditRouteImport } from './routes/_app/messages/$messageId/edit'
import { Route as AppMessagesSettingsIndexRouteImport } from './routes/_app/messages/settings/index'
import { Route as AppMessagesTemplatesIndexRouteImport } from './routes/_app/messages/templates/index'
import { Route as AppAttendanceSectionsSectionIdIndexRouteImport } from './routes/_app/attendance/sections/$sectionId/index'
import { Route as AppAttendanceSectionsSectionIdMonthRouteImport } from './routes/_app/attendance/sections/$sectionId/month'
import { Route as AppExamsReportCardsSectionsSectionIdRouteImport } from './routes/_app/exams/report-cards/sections/$sectionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessUnavailableRoute = AccessUnavailableRouteImport.update({
  id: '/access-unavailable',
  path: '/access-unavailable',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectSchoolRoute = SelectSchoolRouteImport.update({
  id: '/select-school',
  path: '/select-school',
  getParentRoute: () => rootRouteImport,
} as any)
const TestCodesRoute = TestCodesRouteImport.update({
  id: '/test-codes',
  path: '/test-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AccountChangePasswordRoute = AccountChangePasswordRouteImport.update({
  id: '/account/change-password',
  path: '/account/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/account/security',
  path: '/account/security',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaSetupRoute = MfaSetupRouteImport.update({
  id: '/mfa/setup',
  path: '/mfa/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaVerifyRoute = MfaVerifyRouteImport.update({
  id: '/mfa/verify',
  path: '/mfa/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAttendanceIndexRoute = AppAttendanceIndexRouteImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => AppRoute,
} as any)
const AppExamsIndexRoute = AppExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => AppRoute,
} as any)
const AppExamsExamIdRoute = AppExamsExamIdRouteImport.update({
  id: '/exams/$examId',
  path: '/exams/$examId',
  getParentRoute: () => AppRoute,
} as any)
const AppFeesIndexRoute = AppFeesIndexRouteImport.update({
  id: '/fees/',
  path: '/fees/',
  getParentRoute: () => AppRoute,
} as any)
const AppFeesCollectionsRoute = AppFeesCollectionsRouteImport.update({
  id: '/fees/collections',
  path: '/fees/collections',
  getParentRoute: () => AppRoute,
} as any)
const AppFeesSetupRoute = AppFeesSetupRouteImport.update({
  id: '/fees/setup',
  path: '/fees/setup',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesIndexRoute = AppMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesNewRoute = AppMessagesNewRouteImport.update({
  id: '/messages/new',
  path: '/messages/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAuditLogRoute = AppSettingsAuditLogRouteImport.update({
  id: '/settings/audit-log',
  path: '/settings/audit-log',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRolesRoute = AppSettingsRolesRouteImport.update({
  id: '/settings/roles',
  path: '/settings/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupAcademicYearsRoute = AppSetupAcademicYearsRouteImport.update({
  id: '/setup/academic-years',
  path: '/setup/academic-years',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupClassesRoute = AppSetupClassesRouteImport.update({
  id: '/setup/classes',
  path: '/setup/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupHolidaysRoute = AppSetupHolidaysRouteImport.update({
  id: '/setup/holidays',
  path: '/setup/holidays',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupSchoolRoute = AppSetupSchoolRouteImport.update({
  id: '/setup/school',
  path: '/setup/school',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupSubjectsRoute = AppSetupSubjectsRouteImport.update({
  id: '/setup/subjects',
  path: '/setup/subjects',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffIndexRoute = AppStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffStaffIdRoute = AppStaffStaffIdRouteImport.update({
  id: '/staff/$staffId',
  path: '/staff/$staffId',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffNewRoute = AppStaffNewRouteImport.update({
  id: '/staff/new',
  path: '/staff/new',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsIndexRoute = AppStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsStudentIdRoute = AppStudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsImportRoute = AppStudentsImportRouteImport.update({
  id: '/students/import',
  path: '/students/import',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsNewRoute = AppStudentsNewRouteImport.update({
  id: '/students/new',
  path: '/students/new',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsPromoteRoute = AppStudentsPromoteRouteImport.update({
  id: '/students/promote',
  path: '/students/promote',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableIndexRoute = AppTimetableIndexRouteImport.update({
  id: '/timetable/',
  path: '/timetable/',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetablePeriodsRoute = AppTimetablePeriodsRouteImport.update({
  id: '/timetable/periods',
  path: '/timetable/periods',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableSubstitutionsRoute =
  AppTimetableSubstitutionsRouteImport.update({
    id: '/timetable/substitutions',
    path: '/timetable/substitutions',
    getParentRoute: () => AppRoute,
  } as any)
const AppTimetableTeachersRoute = AppTimetableTeachersRouteImport.update({
  id: '/timetable/teachers',
  path: '/timetable/teachers',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceStaffIndexRoute = AppAttendanceStaffIndexRouteImport.update({
  id: '/attendance/staff/',
  path: '/attendance/staff/',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceStaffStaffIdRoute =
  AppAttendanceStaffStaffIdRouteImport.update({
    id: '/attendance/staff/$staffId',
    path: '/attendance/staff/$staffId',
    getParentRoute: () => AppRoute,
  } as any)
const AppAttendanceStaffMonthRoute = AppAttendanceStaffMonthRouteImport.update({
  id: '/attendance/staff/month',
  path: '/attendance/staff/month',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceStudentsStudentIdRoute =
  AppAttendanceStudentsStudentIdRouteImport.update({
    id: '/attendance/students/$studentId',
    path: '/attendance/students/$studentId',
    getParentRoute: () => AppRoute,
  } as any)
const AppExamsPapersPaperIdRoute = AppExamsPapersPaperIdRouteImport.update({
  id: '/exams/papers/$paperId',
  path: '/exams/papers/$paperId',
  getParentRoute: () => AppRoute,
} as any)
const AppExamsReportCardsIndexRoute =
  AppExamsReportCardsIndexRouteImport.update({
    id: '/exams/report-cards/',
    path: '/exams/report-cards/',
    getParentRoute: () => AppRoute,
  } as any)
const AppExamsReportCardsVersionIdRoute =
  AppExamsReportCardsVersionIdRouteImport.update({
    id: '/exams/report-cards/$versionId',
    path: '/exams/report-cards/$versionId',
    getParentRoute: () => AppRoute,
  } as any)
const AppExamsSettingsIndexRoute = AppExamsSettingsIndexRouteImport.update({
  id: '/exams/settings/',
  path: '/exams/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppExamsStudentsStudentIdRoute =
  AppExamsStudentsStudentIdRouteImport.update({
    id: '/exams/students/$studentId',
    path: '/exams/students/$studentId',
    getParentRoute: () => AppRoute,
  } as any)
const AppFeesReceiptsReceiptIdRoute =
  AppFeesReceiptsReceiptIdRouteImport.update({
    id: '/fees/receipts/$receiptId',
    path: '/fees/receipts/$receiptId',
    getParentRoute: () => AppRoute,
  } as any)
const AppFeesStudentsStudentIdRoute =
  AppFeesStudentsStudentIdRouteImport.update({
    id: '/fees/students/$studentId',
    path: '/fees/students/$studentId',
    getParentRoute: () => AppRoute,
  } as any)
const AppMessagesMessageIdIndexRoute =
  AppMessagesMessageIdIndexRouteImport.update({
    id: '/messages/$messageId/',
    path: '/messages/$messageId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppMessagesMessageIdEditRoute =
  AppMessagesMessageIdEditRouteImport.update({
    id: '/messages/$messageId/edit',
    path: '/messages/$messageId/edit',
    getParentRoute: () => AppRoute,
  } as any)
const AppMessagesSettingsIndexRoute =
  AppMessagesSettingsIndexRouteImport.update({
    id: '/messages/settings/',
    path: '/messages/settings/',
    getParentRoute: () => AppRoute,
  } as any)
const AppMessagesTemplatesIndexRoute =
  AppMessagesTemplatesIndexRouteImport.update({
    id: '/messages/templates/',
    path: '/messages/templates/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAttendanceSectionsSectionIdIndexRoute =
  AppAttendanceSectionsSectionIdIndexRouteImport.update({
    id: '/attendance/sections/$sectionId/',
    path: '/attendance/sections/$sectionId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAttendanceSectionsSectionIdMonthRoute =
  AppAttendanceSectionsSectionIdMonthRouteImport.update({
    id: '/attendance/sections/$sectionId/month',
    path: '/attendance/sections/$sectionId/month',
    getParentRoute: () => AppRoute,
  } as any)
const AppExamsReportCardsSectionsSectionIdRoute =
  AppExamsReportCardsSectionsSectionIdRouteImport.update({
    id: '/exams/report-cards/sections/$sectionId',
    path: '/exams/report-cards/sections/$sectionId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/access-unavailable': typeof AccessUnavailableRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-school': typeof SelectSchoolRoute
  '/test-codes': typeof TestCodesRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dashboard': typeof AppDashboardRoute
  '/account/change-password': typeof AccountChangePasswordRoute
  '/account/security': typeof AccountSecurityRoute
  '/mfa/setup': typeof MfaSetupRoute
  '/mfa/verify': typeof MfaVerifyRoute
  '/exams/$examId': typeof AppExamsExamIdRoute
  '/fees/collections': typeof AppFeesCollectionsRoute
  '/fees/setup': typeof AppFeesSetupRoute
  '/messages/new': typeof AppMessagesNewRoute
  '/settings/audit-log': typeof AppSettingsAuditLogRoute
  '/settings/roles': typeof AppSettingsRolesRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/setup/academic-years': typeof AppSetupAcademicYearsRoute
  '/setup/classes': typeof AppSetupClassesRoute
  '/setup/holidays': typeof AppSetupHolidaysRoute
  '/setup/school': typeof AppSetupSchoolRoute
  '/setup/subjects': typeof AppSetupSubjectsRoute
  '/staff/$staffId': typeof AppStaffStaffIdRoute
  '/staff/new': typeof AppStaffNewRoute
  '/students/$studentId': typeof AppStudentsStudentIdRoute
  '/students/import': typeof AppStudentsImportRoute
  '/students/new': typeof AppStudentsNewRoute
  '/students/promote': typeof AppStudentsPromoteRoute
  '/timetable/periods': typeof AppTimetablePeriodsRoute
  '/timetable/substitutions': typeof AppTimetableSubstitutionsRoute
  '/timetable/teachers': typeof AppTimetableTeachersRoute
  '/attendance/': typeof AppAttendanceIndexRoute
  '/exams/': typeof AppExamsIndexRoute
  '/fees/': typeof AppFeesIndexRoute
  '/messages/': typeof AppMessagesIndexRoute
  '/staff/': typeof AppStaffIndexRoute
  '/students/': typeof AppStudentsIndexRoute
  '/timetable/': typeof AppTimetableIndexRoute
  '/attendance/staff/$staffId': typeof AppAttendanceStaffStaffIdRoute
  '/attendance/staff/month': typeof AppAttendanceStaffMonthRoute
  '/attendance/students/$studentId': typeof AppAttendanceStudentsStudentIdRoute
  '/exams/papers/$paperId': typeof AppExamsPapersPaperIdRoute
  '/exams/report-cards/$versionId': typeof AppExamsReportCardsVersionIdRoute
  '/exams/students/$studentId': typeof AppExamsStudentsStudentIdRoute
  '/fees/receipts/$receiptId': typeof AppFeesReceiptsReceiptIdRoute
  '/fees/students/$studentId': typeof AppFeesStudentsStudentIdRoute
  '/messages/$messageId/edit': typeof AppMessagesMessageIdEditRoute
  '/attendance/staff/': typeof AppAttendanceStaffIndexRoute
  '/exams/report-cards/': typeof AppExamsReportCardsIndexRoute
  '/exams/settings/': typeof AppExamsSettingsIndexRoute
  '/messages/$messageId/': typeof AppMessagesMessageIdIndexRoute
  '/messages/settings/': typeof AppMessagesSettingsIndexRoute
  '/messages/templates/': typeof AppMessagesTemplatesIndexRoute
  '/attendance/sections/$sectionId/month': typeof AppAttendanceSectionsSectionIdMonthRoute
  '/exams/report-cards/sections/$sectionId': typeof AppExamsReportCardsSectionsSectionIdRoute
  '/attendance/sections/$sectionId/': typeof AppAttendanceSectionsSectionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/access-unavailable': typeof AccessUnavailableRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-school': typeof SelectSchoolRoute
  '/test-codes': typeof TestCodesRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dashboard': typeof AppDashboardRoute
  '/account/change-password': typeof AccountChangePasswordRoute
  '/account/security': typeof AccountSecurityRoute
  '/mfa/setup': typeof MfaSetupRoute
  '/mfa/verify': typeof MfaVerifyRoute
  '/exams/$examId': typeof AppExamsExamIdRoute
  '/fees/collections': typeof AppFeesCollectionsRoute
  '/fees/setup': typeof AppFeesSetupRoute
  '/messages/new': typeof AppMessagesNewRoute
  '/settings/audit-log': typeof AppSettingsAuditLogRoute
  '/settings/roles': typeof AppSettingsRolesRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/setup/academic-years': typeof AppSetupAcademicYearsRoute
  '/setup/classes': typeof AppSetupClassesRoute
  '/setup/holidays': typeof AppSetupHolidaysRoute
  '/setup/school': typeof AppSetupSchoolRoute
  '/setup/subjects': typeof AppSetupSubjectsRoute
  '/staff/$staffId': typeof AppStaffStaffIdRoute
  '/staff/new': typeof AppStaffNewRoute
  '/students/$studentId': typeof AppStudentsStudentIdRoute
  '/students/import': typeof AppStudentsImportRoute
  '/students/new': typeof AppStudentsNewRoute
  '/students/promote': typeof AppStudentsPromoteRoute
  '/timetable/periods': typeof AppTimetablePeriodsRoute
  '/timetable/substitutions': typeof AppTimetableSubstitutionsRoute
  '/timetable/teachers': typeof AppTimetableTeachersRoute
  '/attendance': typeof AppAttendanceIndexRoute
  '/exams': typeof AppExamsIndexRoute
  '/fees': typeof AppFeesIndexRoute
  '/messages': typeof AppMessagesIndexRoute
  '/staff': typeof AppStaffIndexRoute
  '/students': typeof AppStudentsIndexRoute
  '/timetable': typeof AppTimetableIndexRoute
  '/attendance/staff/$staffId': typeof AppAttendanceStaffStaffIdRoute
  '/attendance/staff/month': typeof AppAttendanceStaffMonthRoute
  '/attendance/students/$studentId': typeof AppAttendanceStudentsStudentIdRoute
  '/exams/papers/$paperId': typeof AppExamsPapersPaperIdRoute
  '/exams/report-cards/$versionId': typeof AppExamsReportCardsVersionIdRoute
  '/exams/students/$studentId': typeof AppExamsStudentsStudentIdRoute
  '/fees/receipts/$receiptId': typeof AppFeesReceiptsReceiptIdRoute
  '/fees/students/$studentId': typeof AppFeesStudentsStudentIdRoute
  '/messages/$messageId/edit': typeof AppMessagesMessageIdEditRoute
  '/attendance/staff': typeof AppAttendanceStaffIndexRoute
  '/exams/report-cards': typeof AppExamsReportCardsIndexRoute
  '/exams/settings': typeof AppExamsSettingsIndexRoute
  '/messages/$messageId': typeof AppMessagesMessageIdIndexRoute
  '/messages/settings': typeof AppMessagesSettingsIndexRoute
  '/messages/templates': typeof AppMessagesTemplatesIndexRoute
  '/attendance/sections/$sectionId/month': typeof AppAttendanceSectionsSectionIdMonthRoute
  '/exams/report-cards/sections/$sectionId': typeof AppExamsReportCardsSectionsSectionIdRoute
  '/attendance/sections/$sectionId': typeof AppAttendanceSectionsSectionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/access-unavailable': typeof AccessUnavailableRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-school': typeof SelectSchoolRoute
  '/test-codes': typeof TestCodesRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/account/change-password': typeof AccountChangePasswordRoute
  '/account/security': typeof AccountSecurityRoute
  '/mfa/setup': typeof MfaSetupRoute
  '/mfa/verify': typeof MfaVerifyRoute
  '/_app/exams/$examId': typeof AppExamsExamIdRoute
  '/_app/fees/collections': typeof AppFeesCollectionsRoute
  '/_app/fees/setup': typeof AppFeesSetupRoute
  '/_app/messages/new': typeof AppMessagesNewRoute
  '/_app/settings/audit-log': typeof AppSettingsAuditLogRoute
  '/_app/settings/roles': typeof AppSettingsRolesRoute
  '/_app/settings/users': typeof AppSettingsUsersRoute
  '/_app/setup/academic-years': typeof AppSetupAcademicYearsRoute
  '/_app/setup/classes': typeof AppSetupClassesRoute
  '/_app/setup/holidays': typeof AppSetupHolidaysRoute
  '/_app/setup/school': typeof AppSetupSchoolRoute
  '/_app/setup/subjects': typeof AppSetupSubjectsRoute
  '/_app/staff/$staffId': typeof AppStaffStaffIdRoute
  '/_app/staff/new': typeof AppStaffNewRoute
  '/_app/students/$studentId': typeof AppStudentsStudentIdRoute
  '/_app/students/import': typeof AppStudentsImportRoute
  '/_app/students/new': typeof AppStudentsNewRoute
  '/_app/students/promote': typeof AppStudentsPromoteRoute
  '/_app/timetable/periods': typeof AppTimetablePeriodsRoute
  '/_app/timetable/substitutions': typeof AppTimetableSubstitutionsRoute
  '/_app/timetable/teachers': typeof AppTimetableTeachersRoute
  '/_app/attendance/': typeof AppAttendanceIndexRoute
  '/_app/exams/': typeof AppExamsIndexRoute
  '/_app/fees/': typeof AppFeesIndexRoute
  '/_app/messages/': typeof AppMessagesIndexRoute
  '/_app/staff/': typeof AppStaffIndexRoute
  '/_app/students/': typeof AppStudentsIndexRoute
  '/_app/timetable/': typeof AppTimetableIndexRoute
  '/_app/attendance/staff/$staffId': typeof AppAttendanceStaffStaffIdRoute
  '/_app/attendance/staff/month': typeof AppAttendanceStaffMonthRoute
  '/_app/attendance/students/$studentId': typeof AppAttendanceStudentsStudentIdRoute
  '/_app/exams/papers/$paperId': typeof AppExamsPapersPaperIdRoute
  '/_app/exams/report-cards/$versionId': typeof AppExamsReportCardsVersionIdRoute
  '/_app/exams/students/$studentId': typeof AppExamsStudentsStudentIdRoute
  '/_app/fees/receipts/$receiptId': typeof AppFeesReceiptsReceiptIdRoute
  '/_app/fees/students/$studentId': typeof AppFeesStudentsStudentIdRoute
  '/_app/messages/$messageId/edit': typeof AppMessagesMessageIdEditRoute
  '/_app/attendance/staff/': typeof AppAttendanceStaffIndexRoute
  '/_app/exams/report-cards/': typeof AppExamsReportCardsIndexRoute
  '/_app/exams/settings/': typeof AppExamsSettingsIndexRoute
  '/_app/messages/$messageId/': typeof AppMessagesMessageIdIndexRoute
  '/_app/messages/settings/': typeof AppMessagesSettingsIndexRoute
  '/_app/messages/templates/': typeof AppMessagesTemplatesIndexRoute
  '/_app/attendance/sections/$sectionId/month': typeof AppAttendanceSectionsSectionIdMonthRoute
  '/_app/exams/report-cards/sections/$sectionId': typeof AppExamsReportCardsSectionsSectionIdRoute
  '/_app/attendance/sections/$sectionId/': typeof AppAttendanceSectionsSectionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/access-unavailable'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/select-school'
    | '/test-codes'
    | '/verify-otp'
    | '/dashboard'
    | '/account/change-password'
    | '/account/security'
    | '/mfa/setup'
    | '/mfa/verify'
    | '/exams/$examId'
    | '/fees/collections'
    | '/fees/setup'
    | '/messages/new'
    | '/settings/audit-log'
    | '/settings/roles'
    | '/settings/users'
    | '/setup/academic-years'
    | '/setup/classes'
    | '/setup/holidays'
    | '/setup/school'
    | '/setup/subjects'
    | '/staff/$staffId'
    | '/staff/new'
    | '/students/$studentId'
    | '/students/import'
    | '/students/new'
    | '/students/promote'
    | '/timetable/periods'
    | '/timetable/substitutions'
    | '/timetable/teachers'
    | '/attendance/'
    | '/exams/'
    | '/fees/'
    | '/messages/'
    | '/staff/'
    | '/students/'
    | '/timetable/'
    | '/attendance/staff/$staffId'
    | '/attendance/staff/month'
    | '/attendance/students/$studentId'
    | '/exams/papers/$paperId'
    | '/exams/report-cards/$versionId'
    | '/exams/students/$studentId'
    | '/fees/receipts/$receiptId'
    | '/fees/students/$studentId'
    | '/messages/$messageId/edit'
    | '/attendance/staff/'
    | '/exams/report-cards/'
    | '/exams/settings/'
    | '/messages/$messageId/'
    | '/messages/settings/'
    | '/messages/templates/'
    | '/attendance/sections/$sectionId/month'
    | '/exams/report-cards/sections/$sectionId'
    | '/attendance/sections/$sectionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/access-unavailable'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/select-school'
    | '/test-codes'
    | '/verify-otp'
    | '/dashboard'
    | '/account/change-password'
    | '/account/security'
    | '/mfa/setup'
    | '/mfa/verify'
    | '/exams/$examId'
    | '/fees/collections'
    | '/fees/setup'
    | '/messages/new'
    | '/settings/audit-log'
    | '/settings/roles'
    | '/settings/users'
    | '/setup/academic-years'
    | '/setup/classes'
    | '/setup/holidays'
    | '/setup/school'
    | '/setup/subjects'
    | '/staff/$staffId'
    | '/staff/new'
    | '/students/$studentId'
    | '/students/import'
    | '/students/new'
    | '/students/promote'
    | '/timetable/periods'
    | '/timetable/substitutions'
    | '/timetable/teachers'
    | '/attendance'
    | '/exams'
    | '/fees'
    | '/messages'
    | '/staff'
    | '/students'
    | '/timetable'
    | '/attendance/staff/$staffId'
    | '/attendance/staff/month'
    | '/attendance/students/$studentId'
    | '/exams/papers/$paperId'
    | '/exams/report-cards/$versionId'
    | '/exams/students/$studentId'
    | '/fees/receipts/$receiptId'
    | '/fees/students/$studentId'
    | '/messages/$messageId/edit'
    | '/attendance/staff'
    | '/exams/report-cards'
    | '/exams/settings'
    | '/messages/$messageId'
    | '/messages/settings'
    | '/messages/templates'
    | '/attendance/sections/$sectionId/month'
    | '/exams/report-cards/sections/$sectionId'
    | '/attendance/sections/$sectionId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/accept-invite'
    | '/access-unavailable'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/select-school'
    | '/test-codes'
    | '/verify-otp'
    | '/_app/dashboard'
    | '/account/change-password'
    | '/account/security'
    | '/mfa/setup'
    | '/mfa/verify'
    | '/_app/exams/$examId'
    | '/_app/fees/collections'
    | '/_app/fees/setup'
    | '/_app/messages/new'
    | '/_app/settings/audit-log'
    | '/_app/settings/roles'
    | '/_app/settings/users'
    | '/_app/setup/academic-years'
    | '/_app/setup/classes'
    | '/_app/setup/holidays'
    | '/_app/setup/school'
    | '/_app/setup/subjects'
    | '/_app/staff/$staffId'
    | '/_app/staff/new'
    | '/_app/students/$studentId'
    | '/_app/students/import'
    | '/_app/students/new'
    | '/_app/students/promote'
    | '/_app/timetable/periods'
    | '/_app/timetable/substitutions'
    | '/_app/timetable/teachers'
    | '/_app/attendance/'
    | '/_app/exams/'
    | '/_app/fees/'
    | '/_app/messages/'
    | '/_app/staff/'
    | '/_app/students/'
    | '/_app/timetable/'
    | '/_app/attendance/staff/$staffId'
    | '/_app/attendance/staff/month'
    | '/_app/attendance/students/$studentId'
    | '/_app/exams/papers/$paperId'
    | '/_app/exams/report-cards/$versionId'
    | '/_app/exams/students/$studentId'
    | '/_app/fees/receipts/$receiptId'
    | '/_app/fees/students/$studentId'
    | '/_app/messages/$messageId/edit'
    | '/_app/attendance/staff/'
    | '/_app/exams/report-cards/'
    | '/_app/exams/settings/'
    | '/_app/messages/$messageId/'
    | '/_app/messages/settings/'
    | '/_app/messages/templates/'
    | '/_app/attendance/sections/$sectionId/month'
    | '/_app/exams/report-cards/sections/$sectionId'
    | '/_app/attendance/sections/$sectionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  AccessUnavailableRoute: typeof AccessUnavailableRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SelectSchoolRoute: typeof SelectSchoolRoute
  TestCodesRoute: typeof TestCodesRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  AccountChangePasswordRoute: typeof AccountChangePasswordRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  MfaSetupRoute: typeof MfaSetupRoute
  MfaVerifyRoute: typeof MfaVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-unavailable': {
      id: '/access-unavailable'
      path: '/access-unavailable'
      fullPath: '/access-unavailable'
      preLoaderRoute: typeof AccessUnavailableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-school': {
      id: '/select-school'
      path: '/select-school'
      fullPath: '/select-school'
      preLoaderRoute: typeof SelectSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-codes': {
      id: '/test-codes'
      path: '/test-codes'
      fullPath: '/test-codes'
      preLoaderRoute: typeof TestCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/account/change-password': {
      id: '/account/change-password'
      path: '/account/change-password'
      fullPath: '/account/change-password'
      preLoaderRoute: typeof AccountChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/security': {
      id: '/account/security'
      path: '/account/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa/setup': {
      id: '/mfa/setup'
      path: '/mfa/setup'
      fullPath: '/mfa/setup'
      preLoaderRoute: typeof MfaSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa/verify': {
      id: '/mfa/verify'
      path: '/mfa/verify'
      fullPath: '/mfa/verify'
      preLoaderRoute: typeof MfaVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/attendance/': {
      id: '/_app/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AppAttendanceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exams/': {
      id: '/_app/exams/'
      path: '/exams'
      fullPath: '/exams/'
      preLoaderRoute: typeof AppExamsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exams/$examId': {
      id: '/_app/exams/$examId'
      path: '/exams/$examId'
      fullPath: '/exams/$examId'
      preLoaderRoute: typeof AppExamsExamIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fees/': {
      id: '/_app/fees/'
      path: '/fees'
      fullPath: '/fees/'
      preLoaderRoute: typeof AppFeesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fees/collections': {
      id: '/_app/fees/collections'
      path: '/fees/collections'
      fullPath: '/fees/collections'
      preLoaderRoute: typeof AppFeesCollectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fees/setup': {
      id: '/_app/fees/setup'
      path: '/fees/setup'
      fullPath: '/fees/setup'
      preLoaderRoute: typeof AppFeesSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages/': {
      id: '/_app/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AppMessagesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages/new': {
      id: '/_app/messages/new'
      path: '/messages/new'
      fullPath: '/messages/new'
      preLoaderRoute: typeof AppMessagesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/audit-log': {
      id: '/_app/settings/audit-log'
      path: '/settings/audit-log'
      fullPath: '/settings/audit-log'
      preLoaderRoute: typeof AppSettingsAuditLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/roles': {
      id: '/_app/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AppSettingsRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/users': {
      id: '/_app/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/setup/academic-years': {
      id: '/_app/setup/academic-years'
      path: '/setup/academic-years'
      fullPath: '/setup/academic-years'
      preLoaderRoute: typeof AppSetupAcademicYearsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/setup/classes': {
      id: '/_app/setup/classes'
      path: '/setup/classes'
      fullPath: '/setup/classes'
      preLoaderRoute: typeof AppSetupClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/setup/holidays': {
      id: '/_app/setup/holidays'
      path: '/setup/holidays'
      fullPath: '/setup/holidays'
      preLoaderRoute: typeof AppSetupHolidaysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/setup/school': {
      id: '/_app/setup/school'
      path: '/setup/school'
      fullPath: '/setup/school'
      preLoaderRoute: typeof AppSetupSchoolRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/setup/subjects': {
      id: '/_app/setup/subjects'
      path: '/setup/subjects'
      fullPath: '/setup/subjects'
      preLoaderRoute: typeof AppSetupSubjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff/': {
      id: '/_app/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof AppStaffIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff/$staffId': {
      id: '/_app/staff/$staffId'
      path: '/staff/$staffId'
      fullPath: '/staff/$staffId'
      preLoaderRoute: typeof AppStaffStaffIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff/new': {
      id: '/_app/staff/new'
      path: '/staff/new'
      fullPath: '/staff/new'
      preLoaderRoute: typeof AppStaffNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/': {
      id: '/_app/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AppStudentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/$studentId': {
      id: '/_app/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AppStudentsStudentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/import': {
      id: '/_app/students/import'
      path: '/students/import'
      fullPath: '/students/import'
      preLoaderRoute: typeof AppStudentsImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/new': {
      id: '/_app/students/new'
      path: '/students/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof AppStudentsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/promote': {
      id: '/_app/students/promote'
      path: '/students/promote'
      fullPath: '/students/promote'
      preLoaderRoute: typeof AppStudentsPromoteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timetable/': {
      id: '/_app/timetable/'
      path: '/timetable'
      fullPath: '/timetable/'
      preLoaderRoute: typeof AppTimetableIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timetable/periods': {
      id: '/_app/timetable/periods'
      path: '/timetable/periods'
      fullPath: '/timetable/periods'
      preLoaderRoute: typeof AppTimetablePeriodsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timetable/substitutions': {
      id: '/_app/timetable/substitutions'
      path: '/timetable/substitutions'
      fullPath: '/timetable/substitutions'
      preLoaderRoute: typeof AppTimetableSubstitutionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timetable/teachers': {
      id: '/_app/timetable/teachers'
      path: '/timetable/teachers'
      fullPath: '/timetable/teachers'
      preLoaderRoute: typeof AppTimetableTeachersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance/staff/': {
      id: '/_app/attendance/staff/'
      path: '/attendance/staff'
      fullPath: '/attendance/staff/'
      preLoaderRoute: typeof AppAttendanceStaffIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance/staff/$staffId': {
      id: '/_app/attendance/staff/$staffId'
      path: '/attendance/staff/$staffId'
      fullPath: '/attendance/staff/$staffId'
      preLoaderRoute: typeof AppAttendanceStaffStaffIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance/staff/month': {
      id: '/_app/attendance/staff/month'
      path: '/attendance/staff/month'
      fullPath: '/attendance/staff/month'
      preLoaderRoute: typeof AppAttendanceStaffMonthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance/students/$studentId': {
      id: '/_app/attendance/students/$studentId'
      path: '/attendance/students/$studentId'
      fullPath: '/attendance/students/$studentId'
      preLoaderRoute: typeof AppAttendanceStudentsStudentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exams/papers/$paperId': {
      id: '/_app/exams/papers/$paperId'
      path: '/exams/papers/$paperId'
      fullPath: '/exams/papers/$paperId'
      preLoaderRoute: typeof AppExamsPapersPaperIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exams/report-cards/': {
      id: '/_app/exams/report-cards/'
      path: '/exams/report-cards'
      fullPath: '/exams/report-cards/'
      preLoaderRoute: typeof AppExamsReportCardsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exams/report-cards/$versionId': {
      id: '/_app/exams/report-cards/$versionId'
      path: '/exams/report-cards/$versionId'
      fullPath: '/exams/report-cards/$versionId'
      preLoaderRoute: typeof AppExamsReportCardsVersionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exams/settings/': {
      id: '/_app/exams/settings/'
      path: '/exams/settings'
      fullPath: '/exams/settings/'
      preLoaderRoute: typeof AppExamsSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exams/students/$studentId': {
      id: '/_app/exams/students/$studentId'
      path: '/exams/students/$studentId'
      fullPath: '/exams/students/$studentId'
      preLoaderRoute: typeof AppExamsStudentsStudentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fees/receipts/$receiptId': {
      id: '/_app/fees/receipts/$receiptId'
      path: '/fees/receipts/$receiptId'
      fullPath: '/fees/receipts/$receiptId'
      preLoaderRoute: typeof AppFeesReceiptsReceiptIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fees/students/$studentId': {
      id: '/_app/fees/students/$studentId'
      path: '/fees/students/$studentId'
      fullPath: '/fees/students/$studentId'
      preLoaderRoute: typeof AppFeesStudentsStudentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages/$messageId/': {
      id: '/_app/messages/$messageId/'
      path: '/messages/$messageId'
      fullPath: '/messages/$messageId/'
      preLoaderRoute: typeof AppMessagesMessageIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages/$messageId/edit': {
      id: '/_app/messages/$messageId/edit'
      path: '/messages/$messageId/edit'
      fullPath: '/messages/$messageId/edit'
      preLoaderRoute: typeof AppMessagesMessageIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages/settings/': {
      id: '/_app/messages/settings/'
      path: '/messages/settings'
      fullPath: '/messages/settings/'
      preLoaderRoute: typeof AppMessagesSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages/templates/': {
      id: '/_app/messages/templates/'
      path: '/messages/templates'
      fullPath: '/messages/templates/'
      preLoaderRoute: typeof AppMessagesTemplatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance/sections/$sectionId/': {
      id: '/_app/attendance/sections/$sectionId/'
      path: '/attendance/sections/$sectionId'
      fullPath: '/attendance/sections/$sectionId/'
      preLoaderRoute: typeof AppAttendanceSectionsSectionIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance/sections/$sectionId/month': {
      id: '/_app/attendance/sections/$sectionId/month'
      path: '/attendance/sections/$sectionId/month'
      fullPath: '/attendance/sections/$sectionId/month'
      preLoaderRoute: typeof AppAttendanceSectionsSectionIdMonthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exams/report-cards/sections/$sectionId': {
      id: '/_app/exams/report-cards/sections/$sectionId'
      path: '/exams/report-cards/sections/$sectionId'
      fullPath: '/exams/report-cards/sections/$sectionId'
      preLoaderRoute: typeof AppExamsReportCardsSectionsSectionIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppExamsExamIdRoute: typeof AppExamsExamIdRoute
  AppFeesCollectionsRoute: typeof AppFeesCollectionsRoute
  AppFeesSetupRoute: typeof AppFeesSetupRoute
  AppMessagesNewRoute: typeof AppMessagesNewRoute
  AppSettingsAuditLogRoute: typeof AppSettingsAuditLogRoute
  AppSettingsRolesRoute: typeof AppSettingsRolesRoute
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
  AppSetupAcademicYearsRoute: typeof AppSetupAcademicYearsRoute
  AppSetupClassesRoute: typeof AppSetupClassesRoute
  AppSetupHolidaysRoute: typeof AppSetupHolidaysRoute
  AppSetupSchoolRoute: typeof AppSetupSchoolRoute
  AppSetupSubjectsRoute: typeof AppSetupSubjectsRoute
  AppStaffStaffIdRoute: typeof AppStaffStaffIdRoute
  AppStaffNewRoute: typeof AppStaffNewRoute
  AppStudentsStudentIdRoute: typeof AppStudentsStudentIdRoute
  AppStudentsImportRoute: typeof AppStudentsImportRoute
  AppStudentsNewRoute: typeof AppStudentsNewRoute
  AppStudentsPromoteRoute: typeof AppStudentsPromoteRoute
  AppTimetablePeriodsRoute: typeof AppTimetablePeriodsRoute
  AppTimetableSubstitutionsRoute: typeof AppTimetableSubstitutionsRoute
  AppTimetableTeachersRoute: typeof AppTimetableTeachersRoute
  AppAttendanceIndexRoute: typeof AppAttendanceIndexRoute
  AppExamsIndexRoute: typeof AppExamsIndexRoute
  AppFeesIndexRoute: typeof AppFeesIndexRoute
  AppMessagesIndexRoute: typeof AppMessagesIndexRoute
  AppStaffIndexRoute: typeof AppStaffIndexRoute
  AppStudentsIndexRoute: typeof AppStudentsIndexRoute
  AppTimetableIndexRoute: typeof AppTimetableIndexRoute
  AppAttendanceStaffStaffIdRoute: typeof AppAttendanceStaffStaffIdRoute
  AppAttendanceStaffMonthRoute: typeof AppAttendanceStaffMonthRoute
  AppAttendanceStudentsStudentIdRoute: typeof AppAttendanceStudentsStudentIdRoute
  AppExamsPapersPaperIdRoute: typeof AppExamsPapersPaperIdRoute
  AppExamsReportCardsVersionIdRoute: typeof AppExamsReportCardsVersionIdRoute
  AppExamsStudentsStudentIdRoute: typeof AppExamsStudentsStudentIdRoute
  AppFeesReceiptsReceiptIdRoute: typeof AppFeesReceiptsReceiptIdRoute
  AppFeesStudentsStudentIdRoute: typeof AppFeesStudentsStudentIdRoute
  AppMessagesMessageIdEditRoute: typeof AppMessagesMessageIdEditRoute
  AppAttendanceStaffIndexRoute: typeof AppAttendanceStaffIndexRoute
  AppExamsReportCardsIndexRoute: typeof AppExamsReportCardsIndexRoute
  AppExamsSettingsIndexRoute: typeof AppExamsSettingsIndexRoute
  AppMessagesMessageIdIndexRoute: typeof AppMessagesMessageIdIndexRoute
  AppMessagesSettingsIndexRoute: typeof AppMessagesSettingsIndexRoute
  AppMessagesTemplatesIndexRoute: typeof AppMessagesTemplatesIndexRoute
  AppAttendanceSectionsSectionIdMonthRoute: typeof AppAttendanceSectionsSectionIdMonthRoute
  AppExamsReportCardsSectionsSectionIdRoute: typeof AppExamsReportCardsSectionsSectionIdRoute
  AppAttendanceSectionsSectionIdIndexRoute: typeof AppAttendanceSectionsSectionIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppExamsExamIdRoute: AppExamsExamIdRoute,
  AppFeesCollectionsRoute: AppFeesCollectionsRoute,
  AppFeesSetupRoute: AppFeesSetupRoute,
  AppMessagesNewRoute: AppMessagesNewRoute,
  AppSettingsAuditLogRoute: AppSettingsAuditLogRoute,
  AppSettingsRolesRoute: AppSettingsRolesRoute,
  AppSettingsUsersRoute: AppSettingsUsersRoute,
  AppSetupAcademicYearsRoute: AppSetupAcademicYearsRoute,
  AppSetupClassesRoute: AppSetupClassesRoute,
  AppSetupHolidaysRoute: AppSetupHolidaysRoute,
  AppSetupSchoolRoute: AppSetupSchoolRoute,
  AppSetupSubjectsRoute: AppSetupSubjectsRoute,
  AppStaffStaffIdRoute: AppStaffStaffIdRoute,
  AppStaffNewRoute: AppStaffNewRoute,
  AppStudentsStudentIdRoute: AppStudentsStudentIdRoute,
  AppStudentsImportRoute: AppStudentsImportRoute,
  AppStudentsNewRoute: AppStudentsNewRoute,
  AppStudentsPromoteRoute: AppStudentsPromoteRoute,
  AppTimetablePeriodsRoute: AppTimetablePeriodsRoute,
  AppTimetableSubstitutionsRoute: AppTimetableSubstitutionsRoute,
  AppTimetableTeachersRoute: AppTimetableTeachersRoute,
  AppAttendanceIndexRoute: AppAttendanceIndexRoute,
  AppExamsIndexRoute: AppExamsIndexRoute,
  AppFeesIndexRoute: AppFeesIndexRoute,
  AppMessagesIndexRoute: AppMessagesIndexRoute,
  AppStaffIndexRoute: AppStaffIndexRoute,
  AppStudentsIndexRoute: AppStudentsIndexRoute,
  AppTimetableIndexRoute: AppTimetableIndexRoute,
  AppAttendanceStaffStaffIdRoute: AppAttendanceStaffStaffIdRoute,
  AppAttendanceStaffMonthRoute: AppAttendanceStaffMonthRoute,
  AppAttendanceStudentsStudentIdRoute: AppAttendanceStudentsStudentIdRoute,
  AppExamsPapersPaperIdRoute: AppExamsPapersPaperIdRoute,
  AppExamsReportCardsVersionIdRoute: AppExamsReportCardsVersionIdRoute,
  AppExamsStudentsStudentIdRoute: AppExamsStudentsStudentIdRoute,
  AppFeesReceiptsReceiptIdRoute: AppFeesReceiptsReceiptIdRoute,
  AppFeesStudentsStudentIdRoute: AppFeesStudentsStudentIdRoute,
  AppMessagesMessageIdEditRoute: AppMessagesMessageIdEditRoute,
  AppAttendanceStaffIndexRoute: AppAttendanceStaffIndexRoute,
  AppExamsReportCardsIndexRoute: AppExamsReportCardsIndexRoute,
  AppExamsSettingsIndexRoute: AppExamsSettingsIndexRoute,
  AppMessagesMessageIdIndexRoute: AppMessagesMessageIdIndexRoute,
  AppMessagesSettingsIndexRoute: AppMessagesSettingsIndexRoute,
  AppMessagesTemplatesIndexRoute: AppMessagesTemplatesIndexRoute,
  AppAttendanceSectionsSectionIdMonthRoute:
    AppAttendanceSectionsSectionIdMonthRoute,
  AppExamsReportCardsSectionsSectionIdRoute:
    AppExamsReportCardsSectionsSectionIdRoute,
  AppAttendanceSectionsSectionIdIndexRoute:
    AppAttendanceSectionsSectionIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  AccessUnavailableRoute: AccessUnavailableRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SelectSchoolRoute: SelectSchoolRoute,
  TestCodesRoute: TestCodesRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  AccountChangePasswordRoute: AccountChangePasswordRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  MfaSetupRoute: MfaSetupRoute,
  MfaVerifyRoute: MfaVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
