/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppSettingsAuditLogRouteImport } from './routes/_app/settings/audit-log'
import { Route as AppSettingsRolesRouteImport } from './routes/_app/settings/roles'
import { Route as AppSettingsUsersRouteImport } from './routes/_app/settings/users'
import { Route as AppSetupAcademicYearsRouteImport } from './routes/_app/setup/academic-years'
import { Route as AppSetupClassesRouteImport } from './routes/_app/setup/classes'
import { Route as AppSetupHolidaysRouteImport } from './routes/_app/setup/holidays'
import { Route as AppSetupSchoolRouteImport } from './routes/_app/setup/school'
import { Route as AppSetupSubjectsRouteImport } from './routes/_app/setup/subjects'
import { Route as AppStaffIndexRouteImport } from './routes/_app/staff/index'
import { Route as AppStaffStaffIdRouteImport } from './routes/_app/staff/$staffId'
import { Route as AppStaffNewRouteImport } from './routes/_app/staff/new'
import { Route as AppStudentsIndexRouteImport } from './routes/_app/students/index'
import { Route as AppStudentsStudentIdRouteImport } from './routes/_app/students/$studentId'
import { Route as AppStudentsImportRouteImport } from './routes/_app/students/import'
import { Route as AppStudentsNewRouteImport } from './routes/_app/students/new'
import { Route as AppStudentsPromoteRouteImport } from './routes/_app/students/promote'
import { Route as AppTimetableIndexRouteImport } from './routes/_app/timetable/index'
import { Route as AppTimetablePeriodsRouteImport } from './routes/_app/timetable/periods'
import { Route as AppTimetableSubstitutionsRouteImport } from './routes/_app/timetable/substitutions'
import { Route as AppTimetableTeachersRouteImport } from './routes/_app/timetable/teachers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAuditLogRoute = AppSettingsAuditLogRouteImport.update({
  id: '/settings/audit-log',
  path: '/settings/audit-log',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRolesRoute = AppSettingsRolesRouteImport.update({
  id: '/settings/roles',
  path: '/settings/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupAcademicYearsRoute = AppSetupAcademicYearsRouteImport.update({
  id: '/setup/academic-years',
  path: '/setup/academic-years',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupClassesRoute = AppSetupClassesRouteImport.update({
  id: '/setup/classes',
  path: '/setup/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupHolidaysRoute = AppSetupHolidaysRouteImport.update({
  id: '/setup/holidays',
  path: '/setup/holidays',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupSchoolRoute = AppSetupSchoolRouteImport.update({
  id: '/setup/school',
  path: '/setup/school',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupSubjectsRoute = AppSetupSubjectsRouteImport.update({
  id: '/setup/subjects',
  path: '/setup/subjects',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffIndexRoute = AppStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffStaffIdRoute = AppStaffStaffIdRouteImport.update({
  id: '/staff/$staffId',
  path: '/staff/$staffId',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffNewRoute = AppStaffNewRouteImport.update({
  id: '/staff/new',
  path: '/staff/new',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsIndexRoute = AppStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsStudentIdRoute = AppStudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsImportRoute = AppStudentsImportRouteImport.update({
  id: '/students/import',
  path: '/students/import',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsNewRoute = AppStudentsNewRouteImport.update({
  id: '/students/new',
  path: '/students/new',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsPromoteRoute = AppStudentsPromoteRouteImport.update({
  id: '/students/promote',
  path: '/students/promote',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableIndexRoute = AppTimetableIndexRouteImport.update({
  id: '/timetable/',
  path: '/timetable/',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetablePeriodsRoute = AppTimetablePeriodsRouteImport.update({
  id: '/timetable/periods',
  path: '/timetable/periods',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableSubstitutionsRoute =
  AppTimetableSubstitutionsRouteImport.update({
    id: '/timetable/substitutions',
    path: '/timetable/substitutions',
    getParentRoute: () => AppRoute,
  } as any)
const AppTimetableTeachersRoute = AppTimetableTeachersRouteImport.update({
  id: '/timetable/teachers',
  path: '/timetable/teachers',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings/audit-log': typeof AppSettingsAuditLogRoute
  '/settings/roles': typeof AppSettingsRolesRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/setup/academic-years': typeof AppSetupAcademicYearsRoute
  '/setup/classes': typeof AppSetupClassesRoute
  '/setup/holidays': typeof AppSetupHolidaysRoute
  '/setup/school': typeof AppSetupSchoolRoute
  '/setup/subjects': typeof AppSetupSubjectsRoute
  '/staff/$staffId': typeof AppStaffStaffIdRoute
  '/staff/new': typeof AppStaffNewRoute
  '/students/$studentId': typeof AppStudentsStudentIdRoute
  '/students/import': typeof AppStudentsImportRoute
  '/students/new': typeof AppStudentsNewRoute
  '/students/promote': typeof AppStudentsPromoteRoute
  '/timetable/periods': typeof AppTimetablePeriodsRoute
  '/timetable/substitutions': typeof AppTimetableSubstitutionsRoute
  '/timetable/teachers': typeof AppTimetableTeachersRoute
  '/staff/': typeof AppStaffIndexRoute
  '/students/': typeof AppStudentsIndexRoute
  '/timetable/': typeof AppTimetableIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings/audit-log': typeof AppSettingsAuditLogRoute
  '/settings/roles': typeof AppSettingsRolesRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/setup/academic-years': typeof AppSetupAcademicYearsRoute
  '/setup/classes': typeof AppSetupClassesRoute
  '/setup/holidays': typeof AppSetupHolidaysRoute
  '/setup/school': typeof AppSetupSchoolRoute
  '/setup/subjects': typeof AppSetupSubjectsRoute
  '/staff/$staffId': typeof AppStaffStaffIdRoute
  '/staff/new': typeof AppStaffNewRoute
  '/students/$studentId': typeof AppStudentsStudentIdRoute
  '/students/import': typeof AppStudentsImportRoute
  '/students/new': typeof AppStudentsNewRoute
  '/students/promote': typeof AppStudentsPromoteRoute
  '/timetable/periods': typeof AppTimetablePeriodsRoute
  '/timetable/substitutions': typeof AppTimetableSubstitutionsRoute
  '/timetable/teachers': typeof AppTimetableTeachersRoute
  '/staff': typeof AppStaffIndexRoute
  '/students': typeof AppStudentsIndexRoute
  '/timetable': typeof AppTimetableIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings/audit-log': typeof AppSettingsAuditLogRoute
  '/_app/settings/roles': typeof AppSettingsRolesRoute
  '/_app/settings/users': typeof AppSettingsUsersRoute
  '/_app/setup/academic-years': typeof AppSetupAcademicYearsRoute
  '/_app/setup/classes': typeof AppSetupClassesRoute
  '/_app/setup/holidays': typeof AppSetupHolidaysRoute
  '/_app/setup/school': typeof AppSetupSchoolRoute
  '/_app/setup/subjects': typeof AppSetupSubjectsRoute
  '/_app/staff/$staffId': typeof AppStaffStaffIdRoute
  '/_app/staff/new': typeof AppStaffNewRoute
  '/_app/students/$studentId': typeof AppStudentsStudentIdRoute
  '/_app/students/import': typeof AppStudentsImportRoute
  '/_app/students/new': typeof AppStudentsNewRoute
  '/_app/students/promote': typeof AppStudentsPromoteRoute
  '/_app/timetable/periods': typeof AppTimetablePeriodsRoute
  '/_app/timetable/substitutions': typeof AppTimetableSubstitutionsRoute
  '/_app/timetable/teachers': typeof AppTimetableTeachersRoute
  '/_app/staff/': typeof AppStaffIndexRoute
  '/_app/students/': typeof AppStudentsIndexRoute
  '/_app/timetable/': typeof AppTimetableIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/settings/audit-log'
    | '/settings/roles'
    | '/settings/users'
    | '/setup/academic-years'
    | '/setup/classes'
    | '/setup/holidays'
    | '/setup/school'
    | '/setup/subjects'
    | '/staff/$staffId'
    | '/staff/new'
    | '/students/$studentId'
    | '/students/import'
    | '/students/new'
    | '/students/promote'
    | '/timetable/periods'
    | '/timetable/substitutions'
    | '/timetable/teachers'
    | '/staff/'
    | '/students/'
    | '/timetable/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/settings/audit-log'
    | '/settings/roles'
    | '/settings/users'
    | '/setup/academic-years'
    | '/setup/classes'
    | '/setup/holidays'
    | '/setup/school'
    | '/setup/subjects'
    | '/staff/$staffId'
    | '/staff/new'
    | '/students/$studentId'
    | '/students/import'
    | '/students/new'
    | '/students/promote'
    | '/timetable/periods'
    | '/timetable/substitutions'
    | '/timetable/teachers'
    | '/staff'
    | '/students'
    | '/timetable'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/settings/audit-log'
    | '/_app/settings/roles'
    | '/_app/settings/users'
    | '/_app/setup/academic-years'
    | '/_app/setup/classes'
    | '/_app/setup/holidays'
    | '/_app/setup/school'
    | '/_app/setup/subjects'
    | '/_app/staff/$staffId'
    | '/_app/staff/new'
    | '/_app/students/$studentId'
    | '/_app/students/import'
    | '/_app/students/new'
    | '/_app/students/promote'
    | '/_app/timetable/periods'
    | '/_app/timetable/substitutions'
    | '/_app/timetable/teachers'
    | '/_app/staff/'
    | '/_app/students/'
    | '/_app/timetable/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/audit-log': {
      id: '/_app/settings/audit-log'
      path: '/settings/audit-log'
      fullPath: '/settings/audit-log'
      preLoaderRoute: typeof AppSettingsAuditLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/roles': {
      id: '/_app/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AppSettingsRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/users': {
      id: '/_app/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/setup/academic-years': {
      id: '/_app/setup/academic-years'
      path: '/setup/academic-years'
      fullPath: '/setup/academic-years'
      preLoaderRoute: typeof AppSetupAcademicYearsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/setup/classes': {
      id: '/_app/setup/classes'
      path: '/setup/classes'
      fullPath: '/setup/classes'
      preLoaderRoute: typeof AppSetupClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/setup/holidays': {
      id: '/_app/setup/holidays'
      path: '/setup/holidays'
      fullPath: '/setup/holidays'
      preLoaderRoute: typeof AppSetupHolidaysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/setup/school': {
      id: '/_app/setup/school'
      path: '/setup/school'
      fullPath: '/setup/school'
      preLoaderRoute: typeof AppSetupSchoolRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/setup/subjects': {
      id: '/_app/setup/subjects'
      path: '/setup/subjects'
      fullPath: '/setup/subjects'
      preLoaderRoute: typeof AppSetupSubjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff/': {
      id: '/_app/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof AppStaffIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff/$staffId': {
      id: '/_app/staff/$staffId'
      path: '/staff/$staffId'
      fullPath: '/staff/$staffId'
      preLoaderRoute: typeof AppStaffStaffIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff/new': {
      id: '/_app/staff/new'
      path: '/staff/new'
      fullPath: '/staff/new'
      preLoaderRoute: typeof AppStaffNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/': {
      id: '/_app/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AppStudentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/$studentId': {
      id: '/_app/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AppStudentsStudentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/import': {
      id: '/_app/students/import'
      path: '/students/import'
      fullPath: '/students/import'
      preLoaderRoute: typeof AppStudentsImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/new': {
      id: '/_app/students/new'
      path: '/students/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof AppStudentsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/promote': {
      id: '/_app/students/promote'
      path: '/students/promote'
      fullPath: '/students/promote'
      preLoaderRoute: typeof AppStudentsPromoteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timetable/': {
      id: '/_app/timetable/'
      path: '/timetable'
      fullPath: '/timetable/'
      preLoaderRoute: typeof AppTimetableIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timetable/periods': {
      id: '/_app/timetable/periods'
      path: '/timetable/periods'
      fullPath: '/timetable/periods'
      preLoaderRoute: typeof AppTimetablePeriodsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timetable/substitutions': {
      id: '/_app/timetable/substitutions'
      path: '/timetable/substitutions'
      fullPath: '/timetable/substitutions'
      preLoaderRoute: typeof AppTimetableSubstitutionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timetable/teachers': {
      id: '/_app/timetable/teachers'
      path: '/timetable/teachers'
      fullPath: '/timetable/teachers'
      preLoaderRoute: typeof AppTimetableTeachersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsAuditLogRoute: typeof AppSettingsAuditLogRoute
  AppSettingsRolesRoute: typeof AppSettingsRolesRoute
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
  AppSetupAcademicYearsRoute: typeof AppSetupAcademicYearsRoute
  AppSetupClassesRoute: typeof AppSetupClassesRoute
  AppSetupHolidaysRoute: typeof AppSetupHolidaysRoute
  AppSetupSchoolRoute: typeof AppSetupSchoolRoute
  AppSetupSubjectsRoute: typeof AppSetupSubjectsRoute
  AppStaffStaffIdRoute: typeof AppStaffStaffIdRoute
  AppStaffNewRoute: typeof AppStaffNewRoute
  AppStudentsStudentIdRoute: typeof AppStudentsStudentIdRoute
  AppStudentsImportRoute: typeof AppStudentsImportRoute
  AppStudentsNewRoute: typeof AppStudentsNewRoute
  AppStudentsPromoteRoute: typeof AppStudentsPromoteRoute
  AppTimetablePeriodsRoute: typeof AppTimetablePeriodsRoute
  AppTimetableSubstitutionsRoute: typeof AppTimetableSubstitutionsRoute
  AppTimetableTeachersRoute: typeof AppTimetableTeachersRoute
  AppStaffIndexRoute: typeof AppStaffIndexRoute
  AppStudentsIndexRoute: typeof AppStudentsIndexRoute
  AppTimetableIndexRoute: typeof AppTimetableIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsAuditLogRoute: AppSettingsAuditLogRoute,
  AppSettingsRolesRoute: AppSettingsRolesRoute,
  AppSettingsUsersRoute: AppSettingsUsersRoute,
  AppSetupAcademicYearsRoute: AppSetupAcademicYearsRoute,
  AppSetupClassesRoute: AppSetupClassesRoute,
  AppSetupHolidaysRoute: AppSetupHolidaysRoute,
  AppSetupSchoolRoute: AppSetupSchoolRoute,
  AppSetupSubjectsRoute: AppSetupSubjectsRoute,
  AppStaffStaffIdRoute: AppStaffStaffIdRoute,
  AppStaffNewRoute: AppStaffNewRoute,
  AppStudentsStudentIdRoute: AppStudentsStudentIdRoute,
  AppStudentsImportRoute: AppStudentsImportRoute,
  AppStudentsNewRoute: AppStudentsNewRoute,
  AppStudentsPromoteRoute: AppStudentsPromoteRoute,
  AppTimetablePeriodsRoute: AppTimetablePeriodsRoute,
  AppTimetableSubstitutionsRoute: AppTimetableSubstitutionsRoute,
  AppTimetableTeachersRoute: AppTimetableTeachersRoute,
  AppStaffIndexRoute: AppStaffIndexRoute,
  AppStudentsIndexRoute: AppStudentsIndexRoute,
  AppTimetableIndexRoute: AppTimetableIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
