import { z } from 'zod'

export const ERROR_STATUS = {
  AUTHENTICATION_REQUIRED: 401,
  SESSION_EXPIRED: 401,
  MFA_REQUIRED: 403,
  FRESH_AUTHENTICATION_REQUIRED: 403,
  SCHOOL_ACCESS_UNAVAILABLE: 403,
  ACCESS_DENIED: 403,
  FEATURE_DISABLED: 403,
  // The password was generated by the school; the person must choose their own first.
  PASSWORD_CHANGE_REQUIRED: 403,
  RESOURCE_NOT_FOUND: 404,
  INVALID_REQUEST: 400,
  INVITATION_UNAVAILABLE: 400,
  VERSION_CONFLICT: 409,
  LAST_OWNER_PROTECTED: 409,
  IDENTITY_LINK_CONFLICT: 409,
  NOT_ALLOWED_YET: 409,
  RATE_LIMITED: 429,
  SERVICE_UNAVAILABLE: 503,
} as const
export const ErrorCode = z.enum(Object.keys(ERROR_STATUS) as [keyof typeof ERROR_STATUS, ...(keyof typeof ERROR_STATUS)[]])
export type ErrorCode = z.infer<typeof ErrorCode>

/**
 * Why a request the caller was allowed to make was still refused, for the few
 * refusals a person can act on. The list is closed: a reason names a kind of
 * blocker ("this class still has sections"), never a record, a count or a name.
 */
export const ErrorReason = z.enum([
  'grade_has_sections',
  'grade_has_subjects',
  'grade_has_bell_schedule',
  'section_has_students',
  'section_has_teachers',
  'section_has_timetable',
  'section_has_substitutions',
  'section_has_access_rules',
  'subject_has_classes',
  'subject_has_teachers',
  'subject_has_timetable',
  'subject_has_substitutions',
  'fee_head_in_use',
  'fee_structure_has_payments',
  'fee_opt_in_has_payments',
  'fee_amount_exceeds_balance',
  'fee_receipt_already_reversed',
  'fee_nothing_charged',
  'attendance_date_outside_year',
  'attendance_not_a_school_day',
  'attendance_date_in_future',
  'attendance_marking_window_closed',
  'attendance_pupil_not_on_roster',
  'attendance_roster_incomplete',
  'attendance_month_outside_year',
  'staff_attendance_own_record',
  'staff_attendance_not_on_register',
  'staff_attendance_register_incomplete',
  'exam_dates_outside_year',
  'exam_already_published',
  'exam_nothing_to_publish',
  'exam_not_started',
  'exam_recheck_deadline_passed',
  'exam_change_needs_reason',
  'exam_mark_above_maximum',
  'exam_component_not_in_exam',
  'exam_pupil_not_on_roster',
  'exam_publish_before_deadline',
  'exam_section_incomplete',
  'grade_bands_overlap',
  'grade_bands_gap',
  'grade_bands_out_of_range',
  'grade_bands_duplicate_label',
  'report_card_exams_not_published',
  'report_card_exams_changed',
  'report_card_nothing_to_publish',
  'report_card_pupil_not_on_roster',
  'message_not_editable',
  'message_not_sent',
  'message_schedule_in_past',
  'message_schedule_too_far',
  'message_audience_empty',
  'message_placeholder_unknown',
  'message_attachment_too_large',
  'message_attachment_type',
  'message_too_many_attachments',
  'message_template_archived',
  'message_template_kind_mismatch',
  'student_login_not_eligible',
  'student_login_no_guardian_phone',
  'student_login_exists',
  'student_login_missing',
])
export type ErrorReason = z.infer<typeof ErrorReason>

/** Do not include database errors, rejected values, records or tokens in this envelope. */
export const ApiError = z.strictObject({
  error: z.strictObject({
    code: ErrorCode,
    reason: ErrorReason.optional(),
    message: z.string().min(1).max(500),
    requestId: z.string().min(1).max(128),
    retryAfterSeconds: z.number().int().positive().max(86_400).optional(),
  }),
})
export type ApiError = z.infer<typeof ApiError>
